### ISSUE TITLE
Expose opset cache getter method in proxy

### ISSUE THREAD

**Issue by mattkrick** [automerge/automerge#106]
For deeply nested objects,  it's difficult to maintain the path to get a particular object, especially as parents get spliced.
Instead, I propose a method that allows one to get an object by it's `_objectId`.

Current: `doc.foo.bar[5].baz[3].insertAt(0, 'val')`
Proposed: `doc._get(baz3UUID).insertAt(0, 'val')`

For me, it'd be much easier to keep track of an immutable ID vs. a mutable path to the object.

Thanks for automerge!

**Comment by j-f1** [comment]
Perhaps it could be set up to take either a direct `_objectId` or an object with a `_objectId` key to allow passing an old version of the object to find & modify it in the latest doc.

**Comment by kpruden** [comment]
FWIW, this is technically possible, although it's not the most user-friendly API:
```
doc._state.getIn(['opSet', 'cache', 'e5fbb189-0f84-4d4f-880e-c4505ca408ee'])
```

**Comment by kpruden** [comment]
It doesn't look like there's a way to do this. As a workaround, I maintain a objectId -> object mapping within my document itself:
```
let doc = Automerge.init();
doc = Automerge.change(doc, doc => {
  doc.objects = {};
  doc.temp = { foo: 'bar' }; // doc.temp is assigned an _objectId at this point
  doc.objects[doc.temp._objectId] = doc.temp;
  delete doc.temp;
});
```
This works pretty well, although you end up with a couple redundant operations in your history for the set/delete of `doc.temp`

**Comment by mattkrick** [comment]
i'm afraid that making a duplicate of the cache object is just too much of a hack for me. Happy to write a PR  if this is something that'll get merged!
