### ISSUE TITLE
Changing nothing should result in same document

### ISSUE THREAD

**Issue by jezell** [automerge/automerge#113]
Shouldn't this be true?

`doc == Automerge.change(doc, () => {})`

Automerge give a different document even if there are no changes made to the document. Had to put a manual dirty flag in my code to throw away the result if there were not any changes made due to some conditional logic within the transaction. Not the end of the world, but doesn't seem like this should cause the document to change.

**Comment by j-f1** [comment]
This was fixed by #111, which should be in the next update.

**Comment by ept** [comment]
Yes, this was fixed in #111, and that PR has been released in Automerge 0.8.0. If you still have trouble after upgrading, please re-open this issue.
