### ISSUE TITLE
Integrating Automerge with MobX for application state management

### ISSUE THREAD

**Issue by mhalle** [automerge/automerge#116]
I've been investigating using automerge to manage application state, which seems promising with the new undo/redo functionality.

I would like to combine the strengths of automerge with the state management features of MobX, making the application reactive to state changes.  This approach effectively splits the flux/redux architecture into first-class state representation and convenient data dependency management.

MobX works by wrapping data structures with "observable" infrastructure that can trigger application callbacks on state changes.  To make automerge and MobX work together, I need to maintain an MobX observable copy of an automerge document.  Updating this observable, inside a MobX transaction, triggers all application updates.

I want to minimize the coupling between the two libraries as much as possible, even at the risk of some extra copying.

So, basically:
```
const mobxState = observable({ ... });
let automergeState = Automerge.init();
automergeState = Automerge.change(automergeState, 'init', doc => Object.assign(doc, mobxState));
// the following code would be wrapped up in a higher level function call in a real app
automergeState = Automerge.change(automergeState, 'do something', doc => doc.title = 'New Title');
mobx.transaction(() => updateMobXState(mobxState, automergeState));

```
This works if `updateMobXState()` is implemented as `Object.assign()`, except that any non-primitives (Arrays, Objects) are always updated and therefore trigger dependency callbacks in MobX whenever `updateMobXState()` is called, irrespective of whether the corresponding `automergeState` members have changed. 

Another option would be for `updateMobXState()` to use `Automerge.diff()` information to update `mobxState`, thereby only touching the parts of the state that have been modified. Is there any easy way to update an external data structure in the same way that the automerge api updates the internal automerge state from diffs?  The reason this copy is needed is to trigger MobX's getters and setters.

Any other thoughts on how this might be done?  

Thanks.

**Comment by lorefnon** [comment]
I currently do the following: 

```
class ViewModel {
    // Track only the reference
    @observable.ref doc = AutoMerge.init(); 

    // Update crdt and update reference 
    makeChange(mutate: (doc: D) => void, msg) {
        const oldDoc = this.document
        const newDoc = AutoMerge.change(oldDoc, msg, mutate)
        this.crdt = newDoc
    }
   
     // Computed values which UI depends on
     @computed
     get name() {
         this.doc.foo;
     }
    
}
```

**Comment by ept** [comment]
Closing this issue as there hasn't been any activity for a while.
