### ISSUE TITLE
Client server websocket synchronization

### ISSUE THREAD

**Issue by CodeWitchBella** [automerge/automerge#117]
I needed server-centric synchronization (to provide access control) so I built one.

Links: [GitLab repo](https://gitlab.com/isabella.skorepova/automerge-client-server) ([github mirror](https://github.com/s-isabella/automerge-client-server)), [Server package](https://www.npmjs.com/package/automerge-server), [Client package](https://www.npmjs.com/package/automerge-client)

It currently provides:
 - loading and saving documents on server-side (via provided functions)
 - It allows different clients to sync different documents
 - Document-level access control (very under-tested)
 - Offline-first client (will sync after reconnect)

I did not (yet) write readme for it but the structure is very simple. Both server and client are single-file and the repository also contains nodejs-based examples on how to use (although client is really intended to be used in browser). 

Server API:
```js
const server = new AutomergeServer({
  // return promise of 
  //  - false (failed to load) 
  //  - or string (loaded saved doc)
  //  - or null (new document)
  loadDocument: (id) => ..., 
  // text is what should be saved (and later returned from load).
  // Doc contains automerge document (usefull for saving in other formats)
  saveDocument: (id, text, doc) => ...,
  // Returns promise of true (access granted) or false (access denied)
  checkAccess: (id, req) => ..., 
})
// in wss.on('connection')
server.handleSocket(ws, req)
```

Client API:
```js
const client = new AutomergeClient({
  // websocket
  socket,
  // string with data which were saved with save. like localStorage.getItem('automerge')
  savedData, 
  // function which accepts string to save
  save: data => ...,
  // called when doc changes (locally or remotely)
  onChange: (id, doc) => ...,
})
client.subscribe(['a', 'b']) // begins sync of a and b
client.change('a', doc => ...) // changes document a
```

What do you think? Thanks for feedback :smiley: 

Edit: updated embedded code formatting to fit the width of the comment
Edit: syntax highlight

**Comment by ept** [comment]
Hi @s-isabella, thank you for making this! At first glance it looks very useful. I will look at the code in more detail in the next few days.

I notice this is your first open source contribution on GitHub — welcome to the community! 😄🎉

**Comment by aecostas** [comment]
Hi! I have just found automerge today and, after reading a bit about it, I was wondering if server synchronization was available and just found this issue. 

The use cases I was considering were:
   - when a new client joins and nobody is online, is there a "copy" of the transactions in a server, so she/he is able to reply the session? Think, for instance, of a shared whiteboard application for eLearning environment: a student unable to attend to the class at the specific hour may want to reply it later.
    - some scenarios may require a kind of future audit. For instance, an application where a customer and provider fill a form online and a supervisor needs to review some transactions.

Thanks for your work!

**Comment by jsdevtom** [comment]
@ept Thank you so much for this project! @CodeWitchBella Thank you for your implementation.

@aecostas I am also trying to do this. Synchronizing between offline-first clients and the server seems quite complex to me. My initial guess at achieving synchronization would have been to (basically lean on `Automerge.diff`) like so:

1. Store the state as a string in the database (or where ever) with `Automerge.save(doc)`
2. When changes come in from the clients to the server, read the whole document from the database and update said document from the database with `docReadFromDb = Automerge.applyChanges(docReadFromDb, changesFromAClient)` and then store `docReadFromDb` in the database. Then emit the changes that came in to the other online clients.
3. When the offline clients come back online, get them to send me their local `Document`. I would then find difference with `Automerge.diff(docFromClient, docFromServer)` and send this difference to the client. The client would then apply this diff.

I don't know how to apply this difference however. My concrete questions are:
1. Is there a way to apply the diff?
2. Are there flaws in my thinking or understanding and if so, where is the flaw?

**Comment by tw00** [comment]
@CodeWitchBella 

Hey, thanks for creating this great example

I'm running  into an issue here after updating to the newest version of automerge:

```
TypeError: Cannot read property 'getIn' of undefined
    at lessOrEqual (/Users/tw/Projects/automerge-client-server/packages/automerge-client/main.js:7:30)
    at /Users/tw/Projects/automerge-client-server/packages/automerge-client/main.js:80:32
```

This seems to be related to an update in immutable-js and the changes discussed here: https://github.com/automerge/automerge/issues/47

I'm not sure I fully understand the purpose of the `lessOrEqual` function. Can anybody explain this? Again, thanks for all the great work here!

**Comment by gsw945** [comment]
meet same problem again
![image](https://user-images.githubusercontent.com/6281968/92880231-62268f80-f440-11ea-9965-23f7af50dfc2.png)

**Comment by gsw945** [comment]
@tw00 
I solved the problem, `lessOrEqual()` function for new version automerge as below:
```javascript
function lessOrEqual(doc1, doc2) {
  const clock1 = Automerge.Frontend.getBackendState(doc1).getIn(['opSet', 'clock'])
  const clock2 = Automerge.Frontend.getBackendState(doc2).getIn(['opSet', 'clock'])
  return clock1
    .keySeq()
    .concat(clock2.keySeq())
    .reduce(
      (result, key) => result && clock1.get(key, 0) <= clock2.get(key, 0),
      true,
    )
}
```

**Comment by ept** [comment]
@gsw945 That looks like a good solution, thanks for sharing. At some point we should add an explicit API for getting a document's vector clock, rather than having to dig around in the internal data structures like this, but this will do for the time being.
