### ISSUE TITLE
[C-Binding] Get resulting binary change when apply local change

### ISSUE THREAD

**Issue by lightsprint09** [automerge/automerge#125]
The JS version  of [applyLocalChanges](https://github.com/automerge/automerge/blob/2abe94e9e6a35742f1dbd6be12b3d4f3c3cbd880/backend/backend.js#L122) supports returning the resulting binary change. Would be great if can expose this to the C-API

**Comment by jeffa5** [comment]
Hi @lightsprint09, thanks for the report. The Rust version of that function indeed does return the change so this should be wired through to the C code too I think.

**Comment by orionz** [comment]
The old C api has been end of lifed.  A new one is currently being re-written and will be released soon.   See progress in the new main branch.

**Comment by orionz** [comment]
this is old - we have a new c implementation now
