### ISSUE TITLE
Backend.init does not use actorId

### ISSUE THREAD

**Issue by constfun** [automerge/automerge#135]
I see references to `Backend.init` pass in an `actorId`:
https://github.com/automerge/automerge/blob/master/src/automerge.js#L13
https://github.com/automerge/automerge/blob/master/test/backend_test.js#L14
https://github.com/automerge/automerge/blob/master/test/frontend_test.js#L222

The argument isn't used:
https://github.com/automerge/automerge/blob/master/backend/index.js#L123

**Comment by ept** [comment]
@constfun Thanks for pointing that out! I have removed the redundant parameter. (The backend used to require the actorId, but that was changed in 6f81967bb9f24bdeedcb68e20c8dc18702d6d29e.)
