### ISSUE TITLE
table remove not work

### ISSUE THREAD

**Issue by mccoysc** [automerge/automerge#143]
[gun.zip](https://github.com/automerge/automerge/files/2689388/gun.zip)

as the attached file:
open the gun.html in browser a and another browser b(must not the same browser: two insatnce of same browser in one computer share the same storage data and in this example we need "NOT SHARE DATA").
in console of browser a:
input: table.rowAdd([1,2]);
then in browser b:
input: table.rowList()
then you can see data is synced.

the issue is the following:
in browser a,input: table.rowRemove();
i expect the "remove" would make in browser b.
but in fact,it not make "remove".

and i'm sure all "changes" got by Automerge.getChanges is applied in browser b.
but it seems that the changes applied to doc in brower b does not work.
what's the problem?

**Comment by mccoysc** [comment]
@pvh

**Comment by mccoysc** [comment]
![1](https://user-images.githubusercontent.com/18025276/50139899-f8ff0000-02dd-11e9-90ad-0937fe6e4d1c.png)
this is the code for rowRemove.
and all changes would be received by browser b and browser b would apply all changes as following:
_this._doc = Automerge.applyChanges(_this._doc, [changedData]);

but it seems the Automerge.applyChanges does not work.

**Comment by ept** [comment]
Sorry, I don't understand what you're trying to do. I unpacked your zip file and opened the enclosed html file, but only get a blank page in Chrome (the dev tools show an error about not being allowed to access localStorage). It contains a megabyte of JavaScript, which I can't look through. In your screenshot I don't have enough context to understand what you're trying to do.

And you say "applyChanges does not work", but you don't say in what way it isn't working — is it throwing an exception, or ignoring the changes, or giving a completely different result? Could you please state your question more precisely?
