### ISSUE TITLE
Intro code: TypeError: dokument.cards is undefine

### ISSUE THREAD

**Issue by pdiveris** [automerge/automerge#154]
Hi there,

I am trying to get my head round automerge by following for starters the steps indicated in the README. I am doing so in the context of a browser, Firefox 66.0.1 on Mac in this instance to be 
precise. Ihave the following in the code:

```
// import Echo from 'laravel-echo'
const Automerge = require('automerge');

var dokument = {cards: []};

// User adds a card
dokument.cards.push({title: 'Reticulate splines', done: false});

// User marks a task as done
dokument.cards[0].done = true;
let dokument1 = Automerge.init();

console.log(dokument1);

dokument1 = Automerge.change(dokument1, 'Add card', dokument => {
    dokument.cards.push({title: 'Rewrite everything in Clojure', done: false})
});
```

What I am getting back is TypeError: dokument.cards is undefined
- on line 16 which refers to 

```
    dokument.cards.push({title: 'Rewrite everything in Clojure', done: false})
```
I have exactly the same issue happening in Chrome 72.0.3626 on mac osx.

Automerge was installed with npm install and appears to be 0.10.0.

Any ideas?

**Comment by aslakhellesoy** [comment]
@pdiveris you can only mutate docs inside a `change` callback.

**Comment by pdiveris** [comment]
But his line 

``
dokument.cards.push({title: 'Rewrite everything in Clojure', done: false})
```
is inside the on change callback:

```
dokument1 = Automerge.change(dokument1, 'Add card', dokument => {
    dokument.cards.push({title: 'Rewrite everything in Clojure', done: false})
});
```

no? I'am sure it's me not understanding it and it should not be an "issue" but any help to understand would be very welcome. Essentially I want to fetch a document from somewhere, initiialise it, mutate it and store it back.

**Comment by pdiveris** [comment]
OK, I've got it. Sorry, it's what happens when looking at code for too many hours and so early in the morning (or late in the night.) Thanks everybody.
