### ISSUE TITLE
Transit and interchangeable serialization

### ISSUE THREAD

**Issue by bkniffler** [automerge/automerge#157]
Hello,
I'm currently trying to wrap my head around usage of transit-js. May I ask why it is being used instead of relying on JSON? The main benefit, as far as I understand, is the minimal footprint of messages. Can't this be achieved with Protocol buffers either?

I've noticed transit-js contributes heavily to the size of umd bundles that use Automerge (https://bundlephobia.com/result?p=transit-js@0.8.861). Would it make sense to implement some adapter functionality that would allow changing serialization/deserialization? It would be fairly easy and similar to the uuid generator overwrite, though I'd love to see the whole transit-js as optional, not default.

What do you think?

**Comment by ept** [comment]
Hi @bkniffler, yeah, there isn't a particularly good reason for using Transit, and it's on its way out. I am working on a new binary file/communication format that will be vastly more compact and will remove Transit from Automerge.

Making the serialization pluggable is an interesting idea; I will see whether it can be done without adding too much complexity. An alternative might be to provide a converter that translates between the new binary format and a more easily human-readable format (for testing and debugging).

**Comment by bkniffler** [comment]
Thats really awesome to hear.

Transit is being used only in 2 places:
https://github.com/automerge/automerge/blob/master/src/automerge.js#L46
https://github.com/automerge/automerge/blob/master/src/automerge.js#L51

So I guess overwriting wouldn't add too much complexity. But if there is a modern and more compact alternative build into Automerge, I'd be perfectly happy either. 

Though you might consider making the new format a different package (and having pluggable serialization), this way people may choose to stick with immutable-transitjs (for existing databases), JSON (for testing or whatever reason) or the new format.

Keep up the great work!

ps. Is there any rough estimate for the new communication format?

**Comment by ept** [comment]
The new format involves various semantic changes and replacing internal data structures, not just a different serialization, so it won't be as straightforward as replacing those two lines. But I am planning to have a tool that will convert data in the current (transit-encoded) format into the new format for backwards compatibility.

No ETA for the new format yet, sorry. It's on the order of weeks, but it depends on what other commitments come up and consume my time.

**Comment by bkniffler** [comment]
Alright, thanks for the info, we can close for now I guess, since my main issue of transit-js being super clunky will be handled with a new, custom communication format.
