### ISSUE TITLE
Best way to get JSON of changed document?

### ISSUE THREAD

**Issue by nthsense** [automerge/automerge#160]
What's the best way to take an Automerge document and get a JSON representation of it?  At present, I use a call to Automerge.change that makes no changes, but that feels like a hack to me:

`let currentState;
        Automerge.change( doc, d=>{
            currentState = Object.assign({}, d );
        });`

Couldn't see anything obvious on the API that would expose the full object.

**Comment by HerbCaudill** [comment]
`Automerge.change()` returns the object. 

```js
let currentState = Automerge.init()
// currentState is {}

currentState = Automerge.change(currentState, d => {
  d.foo = 'bar' 
})
// now currentState is {foo: 'bar'}
```

See [here](https://github.com/automerge/automerge#example-usage) for a more detailed example.

**Comment by nthsense** [comment]
Thanks, Herb.  For some reason I didn’t realize that the document returned by `change` gave you access to that.

I do think a `toJSON` method could still be helpful, for cases when a child property of your document is an instance of `Automerge.Text` or something.  Presently, it seems you have walk the tree yourself and use `text.join(“”)` on any `Text` nodes.  Just a suggestion.  

Thanks for the response!

**Comment by j-f1** [comment]
That could be implemented by adding a `toJSON` method to the `Automerge.Text` class. Then, you would be able to simply run `JSON.stringify(doc)`, and any `Text` objects inside would be converted to strings.

**Comment by nthsense** [comment]
@j-f1 Would the same apply to `Automerge.Table`?  It might be an edge case, but someone could have a Table as a child node of a document.

**Comment by ept** [comment]
Calling `JSON.stringify()` on an Automerge document should work fine. I have just opened #163 to provide `.toJSON()` methods on `Automerge.Counter`, `Automerge.Text`, and `Automerge.Table` so that they get serialized nicely. Does this do what you want?

**Comment by nthsense** [comment]
@ept Looks like a step in the right direction, thanks!  I'll comment further on the pull request.

**Comment by ept** [comment]
I think #163 solves the issue, so I will close this. Please re-open if I misunderstood.
