### ISSUE TITLE
Immutable.js vs Immer

### ISSUE THREAD

**Issue by nthsense** [automerge/automerge#161]
One thing I noticed when I started using Automerge is the stylistic similarity between Automerge.change and the [Immer JS](https://github.com/immerjs/immer) "produce" method.  I went on to read that Automerge uses Immutable.js under the hood.  Have you given any thought to using Immer?  It's only 2kb vs around 50kb for Immutable.

**Comment by coodoo** [comment]
+1 for considering using immer than immutable, which has a much more friendly APIs to work with.

**Comment by ept** [comment]
Automerge's use of Immutable.js is independent from the change API it uses. Immutable.js is currently used only for internal metadata management and not exposed through Automerge's API. I am planning to move this internal metadata to new data structures that will require neither Immutable.js nor Immer, so the dependency will be removed in the future.
