### ISSUE TITLE
Doc size optimizations?

### ISSUE THREAD

**Issue by sethyuan** [automerge/automerge#162]
Automerge is an amazing piece of software. However, I have to complain about the document size, especially when using `Text`.

I don't have accurate numbers, but just a couple of characters can easily take up KBs when persisted via `automerge.save`.

If my understanding is correct, this has to do with how `Text` is implemented underneath. It's generating too much metadata per character (especially IDs?). I'm not sure, can't we do anything to improve it? This makes handling big text documents impractical with Automerge.

**Comment by ept** [comment]
Hi @sethyuan, yes, I am keenly aware of this problem. I have developed a new algorithm for handling text that has vastly lower overhead, but not yet had time to integrate it into Automerge. I hope to do so soon.

**Comment by hkbarton** [comment]
@ept I found this issue too, and it makes developing an online document tool using automerge impractical since a simple document will take up couple MBs to store and communicate between client and server. Is there any chance to prioritize this issue?

**Comment by sethyuan** [comment]
@ept , any progress on implementing the algorithm? perhaps I can help?
