### ISSUE TITLE
Need fix to issue #151. Any plans to release a new version soon?

### ISSUE THREAD

**Issue by achrist** [automerge/automerge#164]
I think I am hitting the same Duplicate ID issue outlined from issue #151 and I noticed it was fixed back in March. Any chance we can get a new version published that includes that fix? 

Fix is #153 and its mentioned in the Change Log under "Unreleased".

Thanks!

**Comment by achrist** [comment]
I just checkd and confirmed that the issue outlined in #151 is indeed the issue I am hitting. :)

**Comment by ept** [comment]
Oh, sorry! I completely forgot to release this. I've just published version 0.10.1 to npm, which includes the fix for #151.

**Comment by achrist** [comment]
@ept Thanks!!!!
