### ISSUE TITLE
Automerge.Connection usage example

### ISSUE THREAD

**Issue by Arinzeokeke** [automerge/automerge#167]
I apologise if this has been asked before but is there an example somewhere of Automerge.Connection being used over 2 nodes? I can't seem to find any and its documentation is sparse

**Comment by HerbCaudill** [comment]
Hey, @Arinzeokeke - have you seen this? https://github.com/automerge/automerge-net

**Comment by ept** [comment]
Yes, [automerge-net](https://github.com/automerge/automerge-net) is probably the easiest starting point — it connects a client and a server using a simple TCP connection, using Automerge.Connection for the sync protocol.
