### ISSUE TITLE
Version on NPM out of sync with Documentation

### ISSUE THREAD

**Issue by izuchukwu** [automerge/automerge#176]
Hello! Just started working with Automerge and ran into an issue with the setup in the readme—namely that after importing Automerge, the suggested initialization method `Automerge.from` didn’t seem to exist. I solved the issue by adding the Github project as a dependency directly, but that’s most likely not the intended path for new adopters. Will npm be kept in sync with changes to `master`?

**Comment by ept** [comment]
Hi @izuchukwu, thanks for pointing this out. For now I have changed the README back to the version that does not use `Automerge.from`. When this feature is released to npm (in the next few days) I'll update the documentation accordingly.

**Comment by ept** [comment]
I have now released Automerge 0.11.0, which includes `Automerge.from`, and I have updated the README accordingly.
