### ISSUE TITLE
Automerge.Text does not have documented insertAt / deleteAt methods

### ISSUE THREAD

**Issue by Gozala** [automerge/automerge#180]
[According to readme](https://github.com/automerge/automerge/blob/a6c74e7c7e088736b9fb9c9f2004b04706a092ca/README.md#text-editing-support) `Text` type should have `.insertAt` / `.deleteAt` methods but as far as I can tell it [has neither](https://github.com/automerge/automerge/blob/a6c74e7c7e088736b9fb9c9f2004b04706a092ca/frontend/text.js)

It's also pretty unclear to me how one would make any changes to the `Text` blocks.

**Comment by Gozala** [comment]
Oh it appears there is a proxy magic makes it so following works:

```js
Automerge.change(Automerge.init(), doc => {
  doc.text = new Automerge.Text()
  doc.text.insertAt(0, 'h', 'e', 'l', 'l', 'o')
  doc.text.deleteAt(0)
  doc.text.insertAt(0, 'H')
})
```

While following

```js
Automerge.change(Automerge.init(), doc => {
  const text = new Automerge.Text()
  text.insertAt(0, 'h', 'e', 'l', 'l', 'o')
  text.deleteAt(0)
  text.insertAt(0, 'H')

 doc.text = text
})
```
throws exception:

```
Uncaught TypeError: text.insertAt is not a function
    at Automerge.change.doc (<anonymous>:3:8)
    at Object.change (index.js:261)
    at Object.change (automerge.js:26)
    at <anonymous>:1:11
```

**Comment by ept** [comment]
Yes, that's correct. At the moment, Automerge.Text objects are immutable by default; they gain their mutability only by being part of a document within a change callback. See also #166. 

However, I understand that this behaviour is confusing. I'll look into changing it. Allowing mutations of a Text object before it is assigned to a document will also enable #170.

**Comment by Gozala** [comment]
I wrote a patch for #166 https://github.com/automerge/automerge/pull/181 which I think would elevate some of the pain, but having those methods available would be still nice. I'll write some of my thoughts on that in a separate comment.

**Comment by Gozala** [comment]
I do find the fact that change handler gets a mutable ref through proxy quite confusing. It is also worth considering that Proxies are fairly slow and JS engines can't really optimize them as well. With that I would like to propose alternative approach.

What if instead for non dictionaries like `Text`, `Array` (List), `Counter` instead instances had multiple states like `new`, `transient`, `persistent`. Where they new if they have not yet being rooted inside the document, transient during "change" transaction, and "persistent" otherwise.

Idea is that all ops on new `new`  instances will just mutate instance in place. If object is in `persistent` state then all mutation operations would just throw exception saying that objects can be only mutated only during a `change` transaction. And in "transient" state mutation operations would be doing more or less what `proxies.js` currently do.

I imagine all non-new object can be assigned some `root` object when currently `objectId` is assigned. Which would have a flag to indicate whether change is active.

**Comment by ept** [comment]
In 94b4921051594a25922485dc99b02ff8cfc63c80 (#181) I changed the behaviour so that modification of Automerge.Text objects no longer goes via the list proxy, but uses explicit methods on the Text class instead. This enables the flow in your example above, i.e. calling `.insertAt` and `.deleteAt` on the Text object before it is assigned to an Automerge document.

**Comment by pvh** [comment]
Thanks!
