### ISSUE TITLE
RGASplit for Automerge.Text

### ISSUE THREAD

**Issue by Gozala** [automerge/automerge#195]
This is related to #193, where I encounter a need for splitting text segments without making delete, insert route. As I was trying to find a solution I came across to [RGASplit paper](https://pages.lip6.fr/Marc.Shapiro/papers/rgasplit-group2016-11.pdf) that happens to be foundation for [xi editor](https://xi-editor.io/docs/crdt-details.html), [atom's collaborative editing feature](https://github.com/atom/teletype-crdt) and their [next generation code editor](https://github.com/atom/xray#text-is-stored-in-a-copy-on-write-crdt).

I think copy-on-write CRDT approach not only has promising performance improvements, but also might offer some good solution for Rich Text modeling due to introduced split operation. I imagine text blocks could be extended with additional metadata where formatting information could be stored and with that it would be possible to represent Rich Text without resorting to marker tokens as described in #193

**Comment by ept** [comment]
The Automerge 1.x binary encoding format (#253) compresses sequential insertions in a way that has much the same effect as RGASplit, while keeping the CRDT logic simpler. Also, for formatting metadata we now have cursors (#313). I think that addresses everything in this issue, so I'm going to close it.
