### ISSUE TITLE
Delete more than one character

### ISSUE THREAD

**Issue by lightsprint09** [automerge/automerge#197]
I think it would make sense to delete more than one character at the time.

Like:

```javascript
Automerge.change(document, doc => {
  doc.text.deleteAt(10, 4) // I wish javaScript would support named parameters
})
```

**Comment by ept** [comment]
`.deleteAt()` already [takes an optional second argument](https://github.com/automerge/automerge/blob/94b4921051594a25922485dc99b02ff8cfc63c80/frontend/text.js#L95-L99) indicating the number of chars to delete. Does it do what you need?

**Comment by lightsprint09** [comment]
Perfect. Exactly what I was looking for.
