### ISSUE TITLE
TypeError: 'getOwnPropertyDescriptor' on proxy in chrome 76+

### ISSUE THREAD

**Issue by ReasonableDeveloper** [automerge/automerge#205]
Hey, first of all I'd like to thank you for all the hard work on this library. I only recently started using automerge and love the paper + library 😍 	

After chrome was updated last week, I experienced some issues with proxy lists.

I tried replicating the issue in a codesandbox but then realized that there are browser tests validating the exact behavior I'm having trouble with.

Run `yarn build && yarn browsertest` to see following error

```
Chrome 76.0.3809 (Windows 10.0.0) Automerge proxy API list object should support Object.keys() FAILED
  TypeError: 'getOwnPropertyDescriptor' on proxy: trap reported non-configurable and writable for property 'length' which is non-configurable, non-writable in the proxy target
    at Function.keys (<anonymous>)
```

I'm running following software
```
Chrome: 76.0.3809.100
Windows 10: OS Version 1809 (Build 17763.615)
```

**Comment by ReasonableDeveloper** [comment]
I dug into the code with @marcelklehr and found that returning `writable: false` [here](https://github.com/automerge/automerge/blob/master/frontend/proxies.js#L173) makes the test pass. We are uncertain of the implications of this change for the rest of the project though.

**Comment by ept** [comment]
What a curious issue. There must have been some recent change to Chrome that triggered this, since it was never a problem before. In any case I think your fix looks reasonable. Thanks for your contribution!
