### ISSUE TITLE
Detecting conflict

### ISSUE THREAD

**Issue by LostKobrakai** [automerge/automerge#211]
There's `Automerge.getConflicts(doc, key)`, but this means I already need to know the conflicting key. It would be nice to have for example `Automerge.getConflicts(doc)`, which returns `['x']` or even `{x: {'actor-1': 12}}`, so one can detect those conflicts and surface them to the user.

**Comment by ept** [comment]
Yes, this seems useful. For now you can emulate it by querying each key (which ought to be pretty fast):

```js
function getAllConflicts(doc) {
  let conflicts = {}
  for (let key of Object.keys(doc)) {
    conflicts[key] = Automerge.getConflicts(doc, key)
  }
  return conflicts
}
```

**Comment by CodingDive** [comment]
@ept conflicts can also exist deeper in the Automerge document tree right? Is there some way to deeply traverse the whole document to get all the conflicts?

E.g with a document structure like this:

```JavaScript
{
  foo: {
     bar: {
        someList: [],
     }
  }
}
```

How would I detect potential conflicts inside `someList`?

**Comment by ept** [comment]
@CodingDive You can get conflicts on any object by passing the appropriate object to `Automerge.getConflicts()`:

```js
Automerge.getConflicts(doc.foo.bar.someList, 0) // gets conflicts on index 0 of someList
```

**Comment by ept** [comment]
I think the best way of detecting conflicts anywhere in a document is to use the Observable API (#308) to watch patches applied to the root object. Any conflicts are indicated in the patches by having a property with multiple values attached to it. This avoids the need for a separate API for getting conflicts anywhere in the document, and it has the added advantage of providing a notification mechanism for new conflicts, so I will close this issue. Let me know if you need example code for detecting conflicts in this way.
