### ISSUE TITLE
Potential bug: key not set in SkipList#setValue()

### ISSUE THREAD

**Issue by jsdevtom** [automerge/automerge#213]
While browsing the source code, I noticed that at this block:

https://github.com/automerge/automerge/blob/90b79ad5e922baeed7054db0a2074e4af43ac2f8/backend/skip_list.js#L34-L37

the key argument is passed but never used. Instead, `this.key` is used. I can't imagine that this is intentional. If it is, perhaps consider removing the key argument?

**Comment by ept** [comment]
Hi @jsdevtom, thanks for pointing this out! It's correct that the argument is unused, so I have removed it.

**Comment by jsdevtom** [comment]
Hi @ept. Awesome! Thanks for this great library!
