### ISSUE TITLE
Initializing from Snapshot

### ISSUE THREAD

**Issue by ayedo** [automerge/automerge#214]
First of all I would like to thank you for your great work on automerge. It has been a lot of fun playing around with it! 

I don't know a lot about the internals of automerge, so my question might be silly: I was wondering if it's possible to create a doc from a snapshot? The scenario is that I do not want to store all data on all clients. On some I would only want to start from some 'latest' snapshot, and go on from there.

The following naïve test code does not work. The property 'data' is undefined for storeB:
```
import * as automerge from "automerge";

let storeA = automerge.from({ data: [] });

storeA = automerge.change(storeA, doc => {
  doc.data.push({ message: "hello" });;
});

storeA = automerge.change(storeA, doc => {
  doc.data.push({ message: "hello" });;
});

const history = automerge.getHistory(storeA);
const snapshot = history[history.length - 1].snapshot;

let storeB = automerge.from(snapshot);

storeB = automerge.change(storeB, doc => {
  doc.data.push({ message: "world" });
});

storeA = automerge.merge(storeA, storeB);
storeB = automerge.merge(storeB, storeA);
```

**Comment by ept** [comment]
Hi @ayedo, that's a weird issue. I will look into fixing it properly, but for now, a hacky workaround you can use is to do a round-trip via JSON:

```js
let storeB = Automerge.from(JSON.parse(JSON.stringify(snapshot)))
```

However, when you create a new Automerge document this way, you **cannot merge it with the original document** from which you obtained the snapshot. The merge will not throw an error, but it will have a lot of spurious conflicts, because constructing the snapshot has discarded all the CRDT metadata, and so all the merging machinery no longer works.

I guess what we need is a different way of constructing snapshots that retains the ability to be merged with non-snapshotted versions of the document. That will need some careful design work though.

**Comment by ayedo** [comment]
Thanks for your reply, and your workaround, but without merging abilities this defeats what I am trying to achieve.

I'm worried about unbounded growth of the data store. I imagine a document being edited heavily by many clients over years. A new client who would like to participate on the document first has to download a large amount of data before being able to participate. Also every client stores the complete history of the document.

Do you consider this a problem worth pursuing? I've read in another thread that somebody successfully uses gzip on the store, and that there is work being done on optimizing the storage requirements. The one performance test which shows non-linear size growth scared me a bit, but maybe unbounded growth won't be much of a problem in the future after all?

**Comment by ept** [comment]
Hi @ayedo, yes, the unbounded growth is definitely a problem worth fixing. However, this will need to be done internally within the Automerge backend; the snapshots from the `Automerge.getHistory` API are not suitable for this purpose.

My plan is to first introduce a more efficient, compressed storage format that will still retain all history, but represent it in a much more compact way. (I have been working on this on the `performance` branch in this repo.) History pruning is then something we should investigate once this new storage format is in place. I am setting things up with snapshots and history pruning in mind, so they should be fairly easy to implement in the new format.

**Comment by ayedo** [comment]
Hi @ept, that sounds like a good plan. I'll have a look in the performance branch. Let me know if you want some help.

**Comment by ept** [comment]
Closing this issue. We will look into adding proper snapshot support once the performance branch has landed.
