### ISSUE TITLE
possible to enable authentication and read-only access?

### ISSUE THREAD

**Issue by shi-yan** [automerge/automerge#223]
say I want to use this to implement a p2p reddit, only a thread's owner can delete the thread, others can only append to it. How can this be implemented with automerge?

if a malicious client sends a crafted message to delete someone else' thread, how can other clients detect this and reject the change?

**Comment by pvh** [comment]
Automerge is a pure data structure library. It does not define how you should handle networking, distribution or persistence. It's up to you to decide which changes to share or accept. 

The Hypermerge library (part of this github organization) does include P2P data sharing but does not support what you're asking for either.

A system like you are describing could certainly be built using automerge, and if you decide to pursue it, I'm sure we'd all be interested to see it.
