### ISSUE TITLE
New Paper building on Automerge

### ISSUE THREAD

**Issue by winwisely99** [automerge/automerge#226]
https://docsend.com/view/gu3ywqi

https://github.com/textileio/go-threads

We are hiring people in this field to work on this.
https://docs.google.com/document/d/1OWfcLJs0nfLjrl3kTNeuKMHeKJT0-EQU4pseROgI8Uo/edit?usp=sharing

**Comment by pvh** [comment]
I would thank you never to spam github repo issues with recruiting messages.
