### ISSUE TITLE
Reassigning the Entire Document Object

### ISSUE THREAD

**Issue by rlingineni** [automerge/automerge#233]
I'm excited to use this library. As I think about my application, which is a React App using MobX - I don't want to add "change" statements to all of my actions.

```
doc1 = Automerge.change(doc1, 'Add card', doc => {
  doc.cards.push({ title: 'Rewrite everything in Clojure', done: false })
})
```

Alternatively, could I achieve the same effect if I just assign the entire store and Automerge will pickup the changes.
 
```js
doc1 = Automerge.change(doc1, 'Action String that will be populated at runtime', doc => {
 //something like this 
 doc = this.localStore;
  //or maybe
  doc = Object.assign({}.this.localStore)
})
```

Can't wait to use this!

**Comment by rlingineni** [comment]
I think  ssue https://github.com/automerge/automerge/issues/75 answers it for me that it is possible to assign the entire object. I will give it a go.

**Comment by ept** [comment]
Hi @rlingineni, unfortunately, assigning the entire object will not work as expected if several users concurrently update the same document: Automerge will not be able to merge the changes automatically, and will require manual conflict resolution.

Automerge's automatic merging depends on making the changes as fine-grained as possible. That is, if you want to change the value of one property, you only update that one property and nothing else. Automerge currently does not perform a diff to detect which properties have actually changed.

To avoid calls to `Automerge.change` all over your code, you could pass the proxy object `doc` around instead, but I'm not sure that would be much better.
