### ISSUE TITLE
Frontend Tests with mocked Backend

### ISSUE THREAD

**Issue by lightsprint09** [automerge/automerge#246]
For now all Frontend-Automerge tests run through the backend. One could name them integration test. It would be nice to have a test suite which operates on a mocked backend.

I could imagine to use the rust-backend-binary in a Swift port. So I would only port the Automerge Frontend tests with a mocked backend implementation, which would simplify the port.

**Comment by ept** [comment]
Hi @lightsprint09, some of the tests — in particular, those in `test/frontend_test.js` — test only the frontend in isolation, without involving the backend. Those are useful, but I believe the end-to-end "integration" tests are also useful, and I think it's good to have both.

For testing the [Automerge Rust port](https://github.com/automerge/automerge-rs), we have added the facility for the JavaScript backend to be [swapped out](https://github.com/automerge/automerge/commit/6c17526cec9712488e8820083bf0cbc5a36fc71e) for the Rust/WebAssembly implementation. We were then able to run all the tests in this mode, providing good confidence that the new backend is behaving correctly. I think this backend-swapping approach is more effective than mocking out the backend in the tests.
