### ISSUE TITLE
How to undo/delete a non-recent change?

### ISSUE THREAD

**Issue by nickjanssen** [automerge/automerge#254]
Suppose I have a doc consisting of the contents of two files. It looks like this:

```
const doc = Automerge.init({
  bobsFile: 'blah blah',
  johnsFile: 'yadda yadda'
})
```
Now suppose there are two users (Bob and John) both working on their own file, but simultaneously. In other words, `Automerge.getAllChanges` has a list of sequential changes to both files, but randomly scattered. Something like:

* Change to Bobs File
* Change to Bobs File
* Change to Johns File
* Change to Bobs File
* Change to Johns File
* Change to Johns File

How can each user undo their change to their own file, without undoing changes to the other users' file? E.g. how can Bob undo a change to their own file, without affecting John's work?

**Comment by ept** [comment]
Hi @nickjanssen, the way undo currently works in Automerge, a user always only undoes their own changes; they never undo another user's changes. So I think it already does what you want. If not, can you give more detail on the behaviour you're seeing?

**Comment by nickjanssen** [comment]
Sorry if I'm being unclear. I'm developing an application with a virtual file system (something like VS Code). Each file can be edited separately, but I'd like to store the entire file system in one automerge object. Still, if I edit `A.js`, then edit `B.js`, and then go back to `A.js` and press undo, I'd like the undo action to not alter `B.js`.

Here's a more trivial example:
```js
  // Bob and John each have a fruit basket
  let doc = Automerge.from({
    bob: [],
    john: []
  })

  // Bob adds an apple
  doc = Automerge.change(doc, doc => {
    doc.bob.push("apple");
  });

  // John adds a pear
  doc = Automerge.change(doc, doc => {
    doc.john.push("pear");
  });

  // Bob adds an banana
  doc = Automerge.change(doc, doc => {
    doc.bob.push("banana");
  });

  // Actually, John hates pears. How to remove the pear from 
  // John's basket without removing the banana from Bob's basket?

  // undo() removes the banana, not the pear
  doc = Automerge.undo(doc);
```

I'm basically looking for a way to delete a past commit, like you can in git (using git rebase -i). Is this currently impossible?

I'm confused with what you mean by current and other users. I'm writing code locally and there is no network layer. What is a user in this context? Is it `actorId`? How do I tell automerge what user I am when committing?

**Comment by nickjanssen** [comment]
So I finally get it. `Automerge.init()` identifies the user through actorId, and you can verify/set this using `Automerge.getActorId()` and `Automerge.setActorId()`, though these probably aren't needed in practice.

In the case of a networked system, every user just needs to have their own `Automerge.init()` call to identify them, and then they can communicate changes between each other using `Automerge.getChanges()` and `Automerge.applyChanges()`. Thus, `Automerge.undo()` only has effect on each user's own automerge instance. It only removes that user's most recent change, even if later changes from other users (other actorId's) were already applied.

In the example above, John and Bob need to have their own `Automerge.init()` call to make them separate entities. Then they can push fruits like before, but they need to inform eachother using `getChanges()` and `applyChanges()` above. Once they do that, each user can take away their own fruit using `undo()` without affecting the other's.

**Comment by ept** [comment]
Oh, I see. I didn't realise that both files were being edited by the same user (at least the same actor in Automerge terms).

If you want separate undo histories for each file, I think your options currently are:

* Put each file in a separate Automerge document. This is the [approach used in PushPin](https://martin.kleppmann.com/papers/pushpin-papoc20.pdf), and it worked pretty well.
* Create a separate Automerge actor for each document; whenever one actor makes a change, you apply it to the other actors as well. From Automerge's point of view, this is now behaving as if several actors were collaborating over a network, even though in reality they're on the same device. Since each actor maintains a separate undo history, this will allow you to selectively undo changes.
