### ISSUE TITLE
[Question] Documents where objects depend on one another

### ISSUE THREAD

**Issue by jroessel** [automerge/automerge#272]
I'm currently evaluating whether automerge could be used for aiding in implementing a collaborative editor for graphs. Now, graphs have a bit of a problem in that objects are not independent of each other. Edges have a source and a target node, while nodes usually also know the edges at that node. Trying to model that naïvely:

```
doc1 = Automerge.change(doc1, 'Add edge', doc => {
    const edge = { source: doc.nodes[0], target: doc.nodes[1] }
    doc.edges.push(edge)
    doc.nodes[0].outEdges.push(edge)
    doc.nodes[1].inEdges.push(edge)
})
```

yield »Cannot assign an object that already belongs to an Automerge document.«. Alternatively, one could probably use IDs:

```
doc1 = Automerge.change(doc1, 'Add edge', doc => {
    const edge = { id: 1, source: doc.nodes[0].id, target: doc.nodes[1].id }
    doc.edges.push(edge)
    doc.nodes[0].outEdges.push(edge.id)
    doc.nodes[1].inEdges.push(edge.id)
})
```

But now the document of course has no knowledge of the dependencies between objects in the document and if someone were to remove the edge's source node on another device:

```
doc2 = Automerge.change(doc2, 'Delete node', doc => {
  delete doc.nodes[0]
})
```

The merge happily works, without conflicts (as from a _data structure_ point of view there are none, of course), and we'd get the following document:

```
{"nodes":[{"id":2,"shape":"Ellipse","outEdges":[],"inEdges":[1]}],"edges":[{"id":1,"source":1,"target":2}]}
```

Which, from an _application_ point of view has rather glaring problems.

Is there a way of working with such things? Or is there some hook into the merge functionality where I could put custom code to clean up the document or try to rescue what the application would perceive as a conflict, even though the CRDT doesn't?

Or would the preferred way actually be to let `merge` do its thing and afterwards just record another change where cleanup happens that's distributed to the other clients? And basically whenever I call `Automerge.merge` I'd also always check for my definition of conflicts and, if necessary, record another change.

**Comment by ept** [comment]
Hi @jroessel! Good question.

At the moment, I'm afraid Automerge doesn't have a built-in way of representing arbitrary graphs. The best approach is probably to model the graph in the same way as you would in a relational database, that is, with two tables (nodes and edges), where each edge has two foreign keys referencing the start and end nodes of that edge. However, Automerge doesn't currently allow you to express foreign key constraints such as "the start and end node of an edge must exist".

What behaviour do you want in the case where a node deletion conflicts with an edge addition? Do you want both the node and the edge to be deleted (the `ON DELETE CASCADE` behaviour of SQL), or do you want the addition of the edge to resurrect the deleted node? And am I right in thinking that a node without edges is fine, or do you also have a minimum set of edges that a node must have?

My suggestion for implementing this would be to wrap the Automerge document with a model layer that presents the interface and consistency properties that you want. How exactly you do this will depend on the behaviour you want.

Another issue is: assuming that in the Automerge document each edge contains the IDs of the start and end node, how do you efficiently find the incoming/outgoing edges for a particular node? One way of doing this would be by duplicating/denormalising the information (i.e. an edge references the nodes and the nodes also reference the edges), but then you have the problem that the information held by the edges might get inconsistent with the information held by the nodes. In a relational database, you would solve this by having secondary indexes on the edges table, something like this:

```
CREATE TABLE nodes (
  node_id integer PRIMARY KEY,
  properties json
);

CREATE TABLE edges (
  edge_id integer PRIMARY KEY,
  start_node integer REFERENCES nodes (node_id),
  end_node integer REFERENCES nodes (node_id),
  properties json
);

CREATE INDEX edges_tails ON edges (start_node);
CREATE INDEX edges_heads ON edges (end_node);
```

Those last two lines allow you to efficiently find the incoming or outgoing edges at a particular node, without having to duplicate that information in your data model. While Automerge doesn't currently have such a concept of secondary indexes, it is possible to implement such indexes on top of Automerge by hooking into its mechanism for applying patches to a document. If you're interested in this, I can help you work it out in more detail.

**Comment by jroessel** [comment]
Hello, Martin. Sorry for the late reply but in between opening this issue and now I've been sick and on vacation. Our initial (faint) hope was that automerge would be a good way of automatically being able to resolve conflicts with multiple concurrent edits. Our initial prototype used a server component along with locking certain elements for certain users to remain sure that no one can interfere with gestures on a client that has started an editing gesture. And I kinda hoped that a conflict-free client-side way could improve that aspect a lot. But, as I feared and now learned, this only applies to the data structure itself, not the semantics atop of it and we've (for time and other reasons) chosen to remain with the locking strategy along with a dedicated server.

Personally I'd still be interested in how one could implement graph editing on top of automerge, but there's no longer a business need right now ;-), so no need to spend time and go into the details.

(As for your questions, however:

If node deletion conflicts with edge addition one gesture has to give way, of course and the resulting behaviour might either be that the node cannot be deleted (or re-appears as things are reconciled) or that the edge creation gesture is canceled mid-way or it simply vanishes after being created. From a UX standpoint I don't think either option is particularly nice, although one can probably think of indicators or other visual aids to communicate to the user what has happened. So in that sense, I don't think many conflicting gestures have obvious answers as to which gesture should win. Cascading deletion like in SQL would certainly be an option, however.

And yes, nodes can exist standalone, so there shouldn't be many conflicts on _those_ items. However, there are a number of dependent items in the [graph model](https://docs.yworks.com/yfiles-html/dguide/graph), such as ports, labels, edges (which actually attach to ports), which then can cause problems. Especially, as you also pointed out, efficiently knowing which edges attach to which nodes, requires multiple relations between the items in circular ways; our graph implementation has both a list of edges in the graph which know their source/target ports, as well as a list of outgoing and incoming edges on each port. The sample in my initial question was kept deliberately simple, though, while still showing the problematic cases.)
