### ISSUE TITLE
.applyChanges won't apply changes

### ISSUE THREAD

**Issue by natarius** [automerge/automerge#273]
automerge version: 0.14.1

Hi, I am trying to figure out why .applyChanges issn't updating the document

I init my automerge doc like this:
`const doc1 = Automerge.from({ sourceCode: new Automerge.Text() });`

Then I use my own binder for the Monaco Editor to capture user changes and apply them to doc1:

```
function onChange(val: string, event: monacoEditor.editor.IModelContentChangedEvent) {
            const updatedDocument = Automerge.change(doc1, (doc) => {
                event.changes.forEach((change) => {
                    if (change.text === "") {
                        doc.sourceCode.deleteAt(change.rangeOffset, change.rangeLength);
                    } else {
                        [...change.text].forEach((char, index) => {
                            doc.sourceCode.insertAt(index + change.rangeOffset, char);
                        });
                    }
                });
            });

            const changes = Automerge.getChanges(doc1, updatedDocument);

            networkProvider.sent({
                changes: JSON.stringify(changes),
            });
    }
```

Here is the change object this produces:

```
[
   {
      "ops":[
         {
            "action":"ins",
            "obj":"c96dea5d-feaa-4afc-b2cb-14b6bcd9d228",
            "key":"_head",
            "elem":4
         },
         {
            "action":"set",
            "obj":"c96dea5d-feaa-4afc-b2cb-14b6bcd9d228",
            "key":"7afc4310-468d-4faf-b5a3-1b4f6e9ead26:4",
            "value":"t"
         }
      ],
      "actor":"7afc4310-468d-4faf-b5a3-1b4f6e9ead26",
      "seq":4,
      "deps":{

      }
   }
]
```

now when I apply it to a document on another client like so:

```
const doc2 = Automerge.from({ sourceCode: new Automerge.Text() });

const changes = JSON.parse(networkEvent.changes);
const updatedDocument = Automerge.applyChanges(doc2, changes);

```

updatedDocument will not be updated and using Automerge.diff returns []

Can't figure out what the issue is here :(

**Comment by natarius** [comment]
Thanks for getting back!

In my case all clients load the initial state from db

My thinking was for a client to start sending updates to other active clients as the user makes updates and for each client to merge changes into their state seamlessly

Is such scenario not supported then?

**Comment by ept** [comment]
That should be fine! Either take the result of `Automerge.getAllChanges(doc)` and write it to your database, or `Automerge.save(doc)` (which uses a different encoding format, but is functionally equivalent). That's the initial state that each client can use. On each client, use `Automerge.applyChanges()` or `Automerge.load()` (depending on which format you used) to initialise the state, and then clients can start making changes on top of that state.

**Comment by ept** [comment]
I think there is nothing more to be done on this issue, so I'm closing it. Please re-open if there is still a problem.
