### ISSUE TITLE
Compressing history for large text documents

### ISSUE THREAD

**Issue by SahidMiller** [automerge/automerge#277]
@ept I was hoping you had some advice for rolling our own compression. I have a few large Automerge.Text objects in a single document that are very expensive to share on the network as a stream of changes. The majority of the changes related to those text documents have a large set of ops which occurs when a single actor saves a large chunk at once, for example, when creating the initial state of the text object before sharing to others. Any thoughts on compressing these and/or inflating them on the other end?

**Comment by ept** [comment]
@SahidMiller Sorry for the delay. The techniques on #253 make a huge difference here, and I think that binary encoding is the best way forward. In the meantime, until #253 is done, I suggest using a generic compression scheme such as gzip. I don't think it would be worth rolling your own compression at this stage.
