### ISSUE TITLE
removeDoc does not clean up connections' _ourClock caused re-inited document out of sync.

### ISSUE THREAD

**Issue by ulion** [automerge/automerge#303]
automerge have DocSet, and Connections, when any change do any doc happens, it call the handlers (docChanged) of every connections, which then spread the clock of one doc to every other connections no matter which doc is for those connections. For now, it still looks good, if outside frame does not want send unrelated doc clocks, it can filter it out like https://github.com/cudr/slate-collaborative/commit/ab3c36ab7dd7f24059c5d0864735c5892df98028#r45985664 did. But as I commented there, the removeDoc of DocSet is unclean, the clock of the removed doc are still in every other connections' _ourClock cache. which cause the re-inited doc stop sync, and the well known "Unexpected error in receiveOperation RangeError: Cannot pass an old state object to a connection" error.

It is much more related to automerge, not the upper caller. the problem is, what's the clean way to fix this? @ept

**Comment by ept** [comment]
Hi @ulion, thanks for this. On the 1.x release series of Automerge the Automerge.Connection and Automerge.DocSet APIs have been removed, and we are replacing them with new APIs (see #290). We plan to make the first 1.0-preview release soon, and for this reason I am not planning to maintain Automerge.Connection any more.
