### ISSUE TITLE
Automerge.Connection does not communicate changes when packages got lost

### ISSUE THREAD

**Issue by ribx** [automerge/automerge#305]
I experienced problems, where users lost data, because it was not synced to the backend. Turns out, when a package gets lost, e.g. when WiFi disconnects, the Automerge.Connection will not resync correctly.

Here is my test scrip base on jest:

```
import Automerge from 'automerge'

const id = 'id'

const createConnections = (docSet1, docSet2) => {
  if (!docSet1.getDoc(id)) docSet1.setDoc(id, Automerge.init())

  const sendMsg1 = msg => {
    if (connection1.enabled) {
      connection2.receiveMsg(msg)
    }
  }

  const sendMsg2 = msg => {
    if (connection2.enabled) {
      connection1.receiveMsg(msg)
    }
  }

  const connection1 = new Automerge.Connection(docSet1, sendMsg1)
  const connection2 = new Automerge.Connection(docSet2, sendMsg2)

  connection1.enabled = true
  connection2.enabled = true

  connection1.open()
  connection2.open()

  return [connection1, connection2]
}

describe('automerge connection lifecycle', () => {
  it('should allow packet loss with close and open (reconnect)', () => {
    const docSet1 = new Automerge.DocSet()
    const docSet2 = new Automerge.DocSet()

    const [con1] = createConnections(docSet1, docSet2)

    con1.enabled = false

    docSet1.setDoc(
      id,
      Automerge.change(docSet1.getDoc(id), doc => (doc.test1 = true)),
    )

    con1.close()
    con1.enabled = true
    con1.open()

    expect(docSet1.getDoc(id)).toMatchObject({test1: true})
    expect(docSet2.getDoc(id)).toMatchObject({test1: true})
  })

  it('should allow packet loss without reconnect', () => {
    const docSet1 = new Automerge.DocSet()
    const docSet2 = new Automerge.DocSet()

    const [con1] = createConnections(docSet1, docSet2)

    // first create the document at the second connection
    docSet1.setDoc(
      id,
      Automerge.change(docSet1.getDoc(id), doc => (doc.test1 = false)),
    )

    con1.enabled = false

    docSet1.setDoc(
      id,
      Automerge.change(docSet1.getDoc(id), doc => (doc.test1 = true)),
    )

    con1.enabled = true

    docSet2.setDoc(
      id,
      Automerge.change(docSet2.getDoc(id), doc => (doc.test2 = true)),
    )

    expect(docSet1.getDoc(id)).toMatchObject({test1: true, test2: true})
    expect(docSet2.getDoc(id)).toMatchObject({test1: true, test2: true})
  })
})
```

I think the Problem is in https://github.com/automerge/automerge/blob/main/src/connection.js#L66, which assumes the package will always be successful and set "_theirClock" without knowing wether the other side received anything. When the connection is reestablished, the changes made before will still not propagate and the Automerge will (silently?) ignore changes, that are out of order (some actor changes will be missing). Responsible here is also the principle of only raising clocks: https://github.com/automerge/automerge/blob/main/src/connection.js#L10. Should both be abandoned, with the risk of sending changes multiple times?

**Comment by ribx** [comment]
here is a code sandbox: go to the "Tests" tab: https://codesandbox.io/s/busy-dan-kp2tf

**Comment by ept** [comment]
Hi @ribx, thanks for this detailed report. On the 1.x release series of Automerge the Automerge.Connection API has been removed, and we are replacing it with new APIs (see #290). We plan to make the first 1.0-preview release soon, and for this reason I am not planning to maintain Automerge.Connection any more.
