### ISSUE TITLE
`merge` in the performance branch does not behave the same

### ISSUE THREAD

**Issue by dan-weaver** [automerge/automerge#316]
I encountered the following issue using the performance branch.  Although, I'm not certain it's an actual issue or if it's just a difference in the new implementation.  It looks like 2 concurrent changes on the same field results in an error when one of those changes contains a delete.  

```javascript
const A = require("./src/automerge");

const original = A.from({ foo: { bar: "baz" } });

const nodeB = A.applyChanges(A.init(), A.getAllChanges(original));
const nodeA = A.applyChanges(A.init(), A.getAllChanges(original));

const a2 = A.change(nodeA, (d) => {
  d.foo.bar = "foo";
});

const b2 = A.change(nodeB, (d) => {
  delete d.foo;
});


console.log(A.merge(b2, a2).foo)
```

if you run the following code against `main` the merge will work and the logged value will be `undefined` since the value was indeed deleted.  In the performance branch [this](https://github.com/automerge/automerge/blob/performance/backend/op_set.js#L24) error is thrown when we try to merge.

**Comment by ept** [comment]
Thanks for this bug report! I have fixed the problem in faad274204a9913ec2399c2df5f2facf10fa1e9b.
