### ISSUE TITLE
How to merge objects in objects

### ISSUE THREAD

**Issue by ConnysCode** [automerge/automerge#335]
Hey,
Hey, I'm trying to merge two JSON objects. But my problem now is that these objects also contain objects again and I want to join them as well, not overwrite them.

Here is an example:

> My main JSON object
```json
{
    "users": {
        "123": {
            "active": true,
            "password": "12345",
            "settings": {
                "some_setting": true
            }
        },
        "456": {
            "active": false,
            "password": "67891",
            "settings": {
                "some_setting": false
            }
        }
    }
}
```

> My merging JSON Object
```json
{
    "users": {
        "123": {
            "password": "test",
            "settings": {
                "another_setting": "test"
            }
        }
    }
}
```

I would like to get such an object as a result:
```json
{
    "users": {
        "123": {
            "active": true,
            "password": "test",
            "settings": {
                "some_setting": true,
                "another_setting": "test"
            }
        },
        "456": {
            "active": false,
            "password": "67891",
            "settings": {
                "some_setting": false
            }
        }
    }
}
```

I hope you can help me!
Kind regards, conny. 👋🏼

**Comment by skokenes** [comment]
This sounds like a JavaScript question, not an Automerge question? Perhaps try StackOverflow for that, this question has some options for you to consider: https://stackoverflow.com/questions/27936772/how-to-deep-merge-instead-of-shallow-merge

**Comment by ConnysCode** [comment]
Yes! Just thought, it might be possible with automerge. Thanks for the help tho 👍🏼
