### ISSUE TITLE
Gitter chatroom

### ISSUE THREAD

**Issue by schrepfler** [automerge/automerge#35]
It would be nice to have a gitter channel so that we can all collaborate more directly.

**Comment by ept** [comment]
@schrepfler We've got a [Slack channel](https://automerge.slack.com), will that do? I'll send an invitation to the email address on your profile.

(I was trying to set up a public signup page today, but I first need to get admin access from @pvh.)

**Comment by schrepfler** [comment]
I don't mind as long as its easy to subscribe over a link in the README. I think Slack is a bit of an overhead for GitHub as it imposes a channel per team while gitter integrates nicely with any GitHub project and it also can feature the issues and releases feed within the channel.

**Comment by ept** [comment]
Here's a link to sign up to the Slack channel: https://communityinviter.com/apps/automerge/automerge

I think we can stay on Slack for now, as we have a few people there already. But I'll be happy to move to Gitter in the future if there is demand.
