### ISSUE TITLE
Use prettier.io for code formatting?

### ISSUE THREAD

**Issue by joonas-lahtinen** [automerge/automerge#351]
[Prettier](https://prettier.io/) is an _opinionated_ code formatter with a few options (choose between single or double quotes etc.) that lowers the entry to send patches and keeps focus on the code itself by eliminating the need to think about formatting at all.

Would you consider a PR adding such automatic formatting support and converting formatting before alpha 1.0 milestone?

**Comment by pvh** [comment]
Hi Joonas, thanks for asking. I use Prettier on some of my other projects as well, but no, we have discussed and rejected this for now.

**Comment by pvh** [comment]
I will note that we *have* recently adopted an `eslint` style on the soon-to-be-released `performance` branch, but while we may add additional rules which catch bugs (c.f. `radix`), I think we are unlikely to accept pull-requests introducing new rules that change the code style significantly from folks who are not regular contributors.
