### ISSUE TITLE
Support for programmatic change merges.

### ISSUE THREAD

**Issue by mikeal** [automerge/automerge#43]
First of all, great library :)

I'm running in to use cases where I want to display changes and selectively apply them. In order to do so, I need to be able to:

* Get a list of changes changes for a given diff. Basically a more exposed version of `getMissingChanges`.
* An exposed version of `applyChanges`.

Unless I'm missing another way to accomplish this.

**Comment by pvh** [comment]
If I'm reading this right, you want to basically only merge part of the difference between two stores? Can you explain the use-case in more detail so I can understand more intuitively what you're trying to achieve?

Internally, automerge's changes are dependent on being applied to a world-state that has a strict superset of the changes that came before (and ideally as few extra commits as possible). If you could reject one of my commits in your client but I kept working as though it was accepted, I'd start to drift away from your view of reality and wind up with non-convergent data structure.

Now, on the other hand, I can sort of half-imagine a bunch of reasonable situations where you might want to be able to do this, but I think the way to think about it is that it's the moral equivalent of `git rebase`.

**Comment by mikeal** [comment]
At the moment, I just want to add some guards in so that I don't adopt malicious changes. I plan on putting access controls and other constraints on top of this layer but I would like a few "last lines of defense" before I adopt changes.

**Comment by pvh** [comment]
Yes, this is the fundamental challenge with a distributed CRDT. Have you considered making merging new change streams more explicit instead of individual changes?

**Comment by ept** [comment]
I've proposed a simple API for getting and applying changes in #44. Does this do what you need?

I'd like to echo @pvh's warning about selectively applying changes: the CRDT properties hold only if the same set of changes is applied on all nodes. So if you selectively apply some change on one node but not on another, then the nodes will permanently diverge. If you add a filter to reject malicious changes, it's important that all nodes apply the same filter.

**Comment by ept** [comment]
Closing this issue since I think the API introduced in #44 does what you need. Please re-open if that is not the case.
