### ISSUE TITLE
Binary data format version compatibility

### ISSUE THREAD

**Issue by darrenmce** [automerge/automerge#449]
Hi, firstly thanks for this excellent library - on the whole its been an absolute pleasure to work with.

I seem to have ran into my first (potential) gotcha.

I've been using `preview1` and storing documents in binary data format, however upon upgrading to `preview6` it seems it cannot load documents that have non-integers in them.

a small example:

```json
  "dependencies": {
    "automerge": "1.0.1-preview.6",
    "automerge-preview1": "npm:automerge@1.0.1-preview.1"
  }
```

```js
const AutomergePreview6 = require('automerge');
const AutomergePreview1 = require('automerge-preview1');

const oldDoc = AutomergePreview1.from({ num: -931.75 });
AutomergePreview6.load(AutomergePreview1.save(oldDoc));
```

output:
```
RangeError: Invalid length for floating point number: 4
```

I was hoping someone could help me find the best approach in moving forward. Thanks!

**Comment by ept** [comment]
Hi @darrenmce, thanks for bringing this up. This is the result of dropping support for 32-bit floats in #371, but I forgot that this would make earlier documents unreadable. Sorry for that oversight. I will make you a patch to let you upgrade your document with 32-bit floats to 64-bit floats, which should then be compatible with future versions of Automerge.

**Comment by darrenmce** [comment]
Thanks @ept , sounds great.

**Comment by darrenmce** [comment]
Hi @ept, I just tried it out on a few of my documents and it looks good, was able to load them into `preview6` without issue - much appreciated! 

Thanks again!

**Comment by ept** [comment]
Okay, glad to hear it!
