### ISSUE TITLE
Performance when applying changes

### ISSUE THREAD

**Issue by nikgraf** [automerge/automerge#477]
For a presentation I made a small benchmark and now I'm wondering about performance characteristics.

I used the first 10k changes out of the Automerge paper log and did
```
// 47ms
automerge.load(result.doc) // 10k changes

// 643ms
const doc = automerge.load(result.doc) // first 9k changes
automerge.applyChanges(result.changes) // last 1k changes

// 317ms
automerge.applyChanges(result.changes) // 10k changes
```

**I'm wondering why `load` + `applyChanges` is so much slower than just `applyChanges` or am I'm doing something wrong?**

I repeated the same with the full paper (~250k changes) and got these results:
```
// 650ms
automerge.load(result.doc) // 250k changes

// 17098ms
const doc = automerge.load(result.doc) // first 249k changes
automerge.applyChanges(result.changes) // last 1k changes

// 12066ms
automerge.applyChanges(result.changes) // 250k changes
```

The benchmark can be found [here](https://github.com/SerenityNotes/naisho/tree/main/benchmarks/snapshots) and all result came from runs on a M1 Macbook 2020

**Comment by ept** [comment]
Not profiled it yet, but my guess is the following: when you only do `automerge.load`, it directly loads the document content without reconstructing the full change history; I suspect that calling `applyChanges` is forcing the backend to reconstruct the change history and recompute all of the hashes before it can apply the new changes. That change history reconstruction is quite expensive.

In the case where the changes you're applying changes that only depend on the heads of the document that was loaded by `automerge.load`, it should skip the change history reconstruction. I believe the reconstruction should only happen if you apply a change whose dependencies are somewhere further back in the loaded document's history.

It should be possible to be a bit more clever about when the history reconstruction happens. However, we're currently shifting our attention towards the Rust/WebAssembly version of Automerge, which is orders of magnitude faster at applying changes, making this less of a problem.

**Comment by nikgraf** [comment]
thanks for the clarification!
