### ISSUE TITLE
proxy object fails on Object.create(null) object

### ISSUE THREAD

**Issue by koenvanwijk** [automerge/automerge#479]
During the Splash conference I discussed an issue together with Peter about the creation of a proxy object if the object to be serialized is created as follows:
a=Object.create(null)
{}
a.NAME='hi'
'hi'
The problem is that the object 'a' does not have any prototype function.

**Comment by alexjg** [comment]
I'm not able to reproduce this issue as described, would you be able to post some sample code and the error you encounter?

**Comment by koenvanwijk** [comment]
d = Automerge.init()
let newDoc = Automerge.change(d, "", doc => { a=Object.create(null); a.NAME='hi'; doc.b=a})

 Uncaught TypeError: Cannot convert object to primitive value
    at import_value (proxies.js:98:71)
    at Object.set (proxies.js:159:35)
    at eval (eval at render (index.js:1:1), <anonymous>:1:129)
    at _change (index.js:303:9)
    at Module.change (index.js:269:16)

**Comment by orionz** [comment]
The API will only take vanilla javascript objects by design.
