### ISSUE TITLE
Can't install automerge@2.0.0-alpha.3 because it has a dependency on automerge-wasm@0.1.7

### ISSUE THREAD

**Issue by robhicks** [automerge/automerge#512]

**Comment by alexjg** [comment]
Thanks for reporting. I'll yank this release. We're moving over to [@automerge/automerge](https://www.npmjs.com/package/@automerge/automerge) now, the latest release of which (`2.0.0-alpha.4`) should work fine (provided you have a bundler set up to load wasm - examples at https://github.com/automerge/automerge-rs/tree/3989cac40567b43e7f81e8463d4f397aad0caf65/automerge-js/examples)
