### ISSUE TITLE
Does new `Extend` type apply to `unstable.splice`?

### ISSUE THREAD

**Issue by acurrieclark** [automerge/automerge#522]
I see that there is a new `Extend` type which has been introduced for the `ChangeFn`. It seems to me that as the `unstable.splice` function should always be called within a `change` function, it should have the new `Extend` type.

If someone can confirm, will submit a PR. Many thanks.

**Comment by alexjg** [comment]
Intriguing, the `Extend` type was originally introduced to add missing methods to arrays which are only available in the body of the change function, but it does seem to also allow us to enforce that methods can only be called within a change function. That's a nice side effect. I think go ahead and put in the PR.

**Comment by acurrieclark** [comment]
Closing as likely unnecessary
