### ISSUE TITLE
Simultaneous syncing from multiple peers

### ISSUE THREAD

**Issue by acurrieclark** [automerge/automerge#536]
When using the sync protocol over a network (with latency), sync messages from multiple sources can often overlap. This can result in errors when saving and loading a document before a sync "conversation" has completed. eg [this repo](https://github.com/onsetsoftware/automerge-repo-mismatched-heads-example).

This repo simulates 2 peers which are simultaneously updating a document property and then attempt to sync via a central server.

In the repo above, this puts documents into a state which contains one of 3 errors:

1. `duplicate seq {seq-no} found for actor {actor-id}`
2. `invalid changes: changes out of order` (shown when trying to load a saved document)
3. `mismatching heads` (shown when trying to load a saved document)

The first 2 errors tend to occur on the front end (in the example). One of these errors is always found when the error creating sequence is run.

The 3rd error is much harder to reproduce, but does occur sporadically. I have typically seen this when performing a save/load cycle on the server.

**Comment by orionz** [comment]
This looks like a corruption bug that we recently fixed - the latest 0.4.0 rust package should not do this anymore.  If you DO see this behavior in the current package let me know.  If you need help extracting data from any of your corrupt documents let me know, I might be able to help.

**Comment by acurrieclark** [comment]
Thanks @orionz, works perfectly now.

Only test documents were effected, so all good thank you
