### ISSUE TITLE
Identifying conflicts after merge

### ISSUE THREAD

**Issue by mpareja** [automerge/automerge#539]
Is there a way to detect conflicts encountered during an `Automerge.merge` operation without having to walk the entire document tree calling `Automerge.getConflicts`?

I tried hooking into `patchCallbacks` but it does not include patches when the `local` doc's changes are chosen based on lamport timestamp.

**Comment by alexjg** [comment]
There's no API for it built into the document yet, though I think we should add one. Can you post an example of the problem with the `patchCallback` not being called on a conflict? It _should_ be I think so this might be a bug.

**Comment by mpareja** [comment]
Below is a sample that can easily be turned into a test.

```js
let doc1 = Automerge.from({ str: 'first' }, 'b'); // actorId is later than 'a'
let doc2 = Automerge.clone(doc1, 'a');
doc1 = Automerge.change(doc1, (d) => d.str = 'second');
doc2 = Automerge.change(doc2, (d) => d.str = 'third');

const [merged, patches] = mergeAndGetPatch(doc1, doc2);

console.log('CHOSEN', merged.str); // 'second' - doc1's value is chosen because 'b' actor id is later than 'a'
console.log('PATCHES', patches); // [] - no patches recorded since doc1's value is chosen
console.log('CONFLICTS', Automerge.getConflicts(merged, 'str')); // { '2@a1': 'third', '2@a2': 'second' }
```

Regarding your comment about `patchCallback`, I suppose I'm not entire sure how others are using it. I can imagine an argument for the way it's implemented since _nothing actually changed in the document_.

For our use case, it would be convenient if `patchCallback` included the entry. Further to that, it would be useful if I could provide `MergeOptions` like so:

```js
Automerge.merge(local, remote, { patchCallback })`
```

**Comment by mpareja** [comment]
Whoops, missed a function in that test code:
```js
export function mergeAndGetPatch<TData>(
  localDoc: Automerge.Doc<TData>,
  remoteDoc: Automerge.Doc<TData>
): [Automerge.Doc<TData>, ModelPatch[]] {
  // it's recommended we clone this or else the original is not mutable...
  const remoteClone = Automerge.clone(remoteDoc);

  let allPatches = [] as ModelPatch[];
  const patchCallback = (patches: Automerge.Patch[]) => {
    allPatches = allPatches.concat(patches);
  };

  // create a clone with tracking (don't know how else to listen for merges)
  const localWithTracking = Automerge.merge(Automerge.init<TData>({ patchCallback }), localDoc);
  allPatches = []; // reset tracking

  const updatedWithTracking = Automerge.merge(localWithTracking, remoteClone);
  const updatedDoc = Automerge.clone(updatedWithTracking);
  return [updatedDoc, allPatches];
}
```

**Comment by alexjg** [comment]
Hmm, I'll have a closer look at this tomorrow. We did at one point flag conflicts on the patchcallback so even if the winning state didn't change you would get a notification that there is a conflict. We're not doing that anymore, but I suspect the better solution is an API to get the conflicts specifically anyway, rather than a patch callback.

**Comment by orionz** [comment]
Hey.  This information isn't in patch callback but it could be.  I'm going to open a branch to make this information available.  Would you be willing to beta test the change and make sure it meets your needs?

**Comment by mpareja** [comment]
Hi @orionz :wave:. Sure, I can test that patch callback works as we need.

It'll be interesting to see the performance difference between walking the document looking for conflicts vs Clone (with tracking) + Merge + Clone (without tracking).

**Comment by orionz** [comment]
This has been merged into main
