### ISSUE TITLE
Importing automerge-wasm in Vitest results in SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by bravely** [automerge/automerge#556]
While the existing Vite example in the repo causes it to work for a Vite app proper, I can't seem to get past the following error when running any of my app through Vitest:

```
 FAIL  src/Anthology/index.test.ts [ src/Anthology/index.test.ts ]
SyntaxError: Cannot use import statement outside a module
 ❯ Object.<anonymous> ../../node_modules/.pnpm/@automerge+automerge@2.0.2/node_modules/@automerge/automerge/dist/cjs/stable.js:39:14

Module /Users/bravely/couplet/js/node_modules/.pnpm/@automerge+automerge-wasm@0.1.25/node_modules/@automerge/automerge-wasm/bundler/automerge_wasm.js:1 seems to be an ES Module but shipped in a CommonJS package. You might want to create an issue to the package "@automerge/automerge-wasm" asking them to ship the file in .mjs extension or add "type": "module" in their package.json.

As a temporary workaround you can try to inline the package by updating your config:

// vitest.config.js
export default {
  test: {
    deps: {
      inline: [
        "@automerge/automerge-wasm"
      ]
    }
  }
}
```

This is my `vitest.config.ts`:

```ts
import solidPlugin from 'vite-plugin-solid'
import { defineConfig } from 'vitest/config'
import basicSsl from '@vitejs/plugin-basic-ssl'
import topLevelAwait from 'vite-plugin-top-level-await'
import wasm from 'vite-plugin-wasm'

export default defineConfig({
	plugins: [solidPlugin(), basicSsl(), topLevelAwait(), wasm()],
	test: {
		// otherwise, solid would be loaded twice:
		deps: {
			registerNodeLoader: true,
			inline: [/solid-js/, '@automerge/automerge-wasm'],
		},
		environment: 'jsdom',
		globals: true,
		setupFiles: [
			'node_modules/@testing-library/jest-dom/extend-expect',
			'./testSupport/globalSetup.ts',
		],
		transformMode: { web: [/\.[jt]sx?$/] },
	},
	resolve: {
		conditions: ['development', 'browser'],
	},
	// optimizeDeps: {
	// 	exclude: ['@automerge/automerge-wasm'],
	// },
})
```

Note the commented out `optimizeDeps` config- which matches the `vite.config.ts` in the example. I've tried with it not commented, as well as with `'@automerge/automerge-wasm'` not included in `test.deps.inline`, and with neither. None got me a different error.

Curious if there's a genuine issue or any insight that could be provided so I can test what I write with Automerge.

**Comment by acurrieclark** [comment]
I encountered a similar issue today in a Sveltekit app, where the solution (at least to eliminating the error) was to remove the other plugins for my tests.

When only `topLevelAwait` and `wasm` are left, my tests run without issue.

If I get to the bottom of why, I will let you know.

**Comment by bravely** [comment]
Attempted that myself but not getting that behavior, I get the same error regardless.

**Comment by bravely** [comment]
OK, so I've created [a repo reproducing the issue](https://github.com/bravely/automerge-vitest-import-error), and managed to narrow it down to this part of the config:

```ts
    resolve: {
		conditions: ['development', 'browser'],
	},
```

This is needed for me to run SolidJS via Vitest correctly, sorta, but somehow that [Vite config option](https://vitejs.dev/config/shared-options.html#resolve-conditions) is breaking the import with the above error.

**Comment by bravely** [comment]
...and, finally got a fix. For those who follow me: Just remove `'browser'` from the above config, so it instead reads:

```ts
    resolve: {
      conditions: ['development']
    }
```
