### ISSUE TITLE
how does automerge compare to holochain?

### ISSUE THREAD

**Issue by pmualaba** [automerge/automerge#566]
https://developer.holochain.org/concepts/1_the_basics/

**Comment by EzraEn1** [comment]
Hey @pmualaba, Automerge is like Docs. Holochain is Bittorrent.

Both attempt to ensure data integrity in different circumstances.
Automerge (a CRDT) tries to ensure data integrity when two different people are working on the same file at once, solving the problem of data integrity via eventual consistency.
Holochain tries to ensure data integrity of a file across the network. However, if you change the file, it is no longer part of the network consensus and your version of the file is no longer the same file. The network is not interested in your changes and merging them, it is interested in maintaining the ground truth. Hence the "-chain" part. The majority (ledger) is king.

These two bits of software are both interested in maintaining data integrity, but with completely different goals in mind. 

If you'd like to discuss CRDTs more, come over to the [LFW.dev](https://localfirstweb.dev/) Discord. Github Issues isn't the place for discussion like this. You can find it on the website linked.

**Comment by jkankiewicz** [comment]
The most noticeable difference between Automerge and Holochain is that the former doesn't require a specific network and the latter does; Automerge can synchronize data between peers over a LAN.
