### ISSUE TITLE
error inflating document 

### ISSUE THREAD

**Issue by BLukassen** [automerge/automerge#567]
sometimes when I load a binary array with Automerge.load(bin) I get the error:
 'error inflating document chunk ops: mismatching heads'

I use Automerge.save(doc) to get the binary.

Can you give me a hint what the reason may be or how this can happen anways?

**Comment by acurrieclark** [comment]
This could be related to #536. I have found this occurring if a batch of sync messages are applied to a document from different sources. When it is saved and reloaded, the `mismatched heads` error occurs.

**Comment by orionz** [comment]
This looks like a corruption bug that we recently fixed - the latest 0.4.0 rust package should not do this anymore. If you DO see this behavior in the current package let me know. If you need help extracting data from any of your corrupt documents let me know, I might be able to help.
