### ISSUE TITLE
Number conflicts changing after saving/loading document

### ISSUE THREAD

**Issue by vegardok** [automerge/automerge#579]
I've noticed what I think is a bug where the result of a conflict changes after saving/loading the result of merging two documents, shortly summarized: `AM.merge(doc1, doc2).some.deeper.levels.down.x !== AM.load(AM.save(AM.merge(doc1, doc2))).some.deeper.levels.down.x`.
I create a sample app reproducing the issue: https://github.com/vegardok/automerge-bug-repro.
I've observed the issue in both Chrome Version 112.0.5615.137 (Official Build) (x86_64) and Firefox version 112.0.1 (64-bit) on OSX 13.3.1 (22E261).

**Comment by orionz** [comment]
Thanks for this.  Found the bug and will be releasing a new package shortly.

**Comment by orionz** [comment]
@automerge/automerge 2.0.3 is out
