### ISSUE TITLE
Grapheme clusters seem like a dangerous recommendation

### ISSUE THREAD

**Issue by josephg** [automerge/automerge#591]
[The documentation](https://automerge.org/docs/types/text/) for Text objects currently says this:

> Note: Technically, text should be represented as a list of [Unicode grapheme clusters](http://www.unicode.org/reports/tr29/). What the user thinks of as a "character" may actually be a series of several Unicode code points, including accents, diacritics, and other combining marks. A grapheme cluster is the smallest editable unit of text: that is, the thing that gets deleted if you press the delete key once, or the thing that the cursor skips over if you press the right-arrow key once. Emoji make a good test case, since many emoji consist of a sequence of several Unicode code points (for example, the [skintone modifier](http://www.unicode.org/reports/tr51/) is a combining mark).

This seems dangerous! My concern is that grapheme cluster boundaries change depending on the version of the unicode spec your program is using. And that means different operating systems & different programming languages have different ideas of how many grapheme clusters the same text will take up - so cursor positions won't line up across all systems.

As an example, the polar bear emoji (🐻‍❄️) is the result of combining 🐻 Bear, Zero Width Joiner and ❄️ Snowflake. Older computers (eg old debian) might see 3 grapheme clusters (🐻+ZWJ+❄️) while my iphone will see 1. If I place my cursor after a polar bear, on an iphone that would be at position 1. On debian, thats at position 3. And thus, we'll run into desync issues while collaboratively editing.

Or taking the example from the documentation - support for the skintone modifier is rolling out slowly across multiple unicode versions. A document which groups characters using grapheme clusters has a hidden dependency on the exact version of the unicode spec your grapheme-counting library is using.

Thoughts?

My personal take is to use unicode boundaries instead - which is also trivially easy to do in javascript like this:

```javascript
doc.text.insertAt(0, ...[...'hello'])
```

And in rust using `.chars()`. And I assume automerge already supports this because of the way text documents work.

**Comment by josephg** [comment]
I just took a look at the code. Notably, the Text constructor does exactly this when initializing a document:

From [javascript/src/text.ts](https://github.com/automerge/automerge/blob/67d7303e6a30035c445fd5cac9443764bb75f529/javascript/src/text.ts#L16):

```typescript
  constructor(text?: string | string[] | Value[]) {
    if (typeof text === "string") {
      this.elems = [...text] // <---- String is split by unicode characters not grapheme clusters!
    } else if (Array.isArray(text)) {
    // ...
```

**Comment by ept** [comment]
Hi Seph, you're right and we came to the same conclusion. The implementation already operates on Unicode code points, and it's just the documentation that is stale. I've [deleted](https://github.com/automerge/automerge.github.io/commit/a3c742e1ed84ec43a4f4316223f24690cebd6802) that paragraph about grapheme clusters from the docs. Thanks for bringing it up!
