### ISSUE TITLE
Empty marks are returned by marks()

### ISSUE THREAD

**Issue by ConradIrwin** [automerge/automerge#609]
This may be related to #604; currently if you create a mark and then clear half of it then marks will report an empty mark at the start of the string.

This may be useful in the case where inserting text at that location will inherit the mark, but (as in https://github.com/automerge/automerge/commit/f6cefc235e1dcec138ee447a07bf6f690e3ae20b#diff-d822dff8eea94f7201e80ed6a88e0bf89b5f10970198f586cb16ccae63b7f1ceR1714-R1719) it's not useful when newly added text is not affected.

As the expand property of a mark is not introspectable in the current API, it'd be nice to only return marks that would expand if text was inserted there.

**Comment by orionz** [comment]
This gets fixed by #629.  Will be merged soon
