### ISSUE TITLE
[bug] Incorrect before documents in PatchCallback when deleting from a list or object

### ISSUE THREAD

**Issue by acurrieclark** [automerge/automerge#621]
I realised that I should have marked this as an issue too, rather than just as a [PR with a failing test](https://github.com/automerge/automerge/pull/616).

---

When removing an item from a list or deleting an object property, the `before` document in the PatchCallback does not contain the deleted entry.

For example, the following test fails:

```typescript
it("should provide correct before and after states when an array has a value deleted", () => {
  const doc = Automerge.from<{ list: string[] }>({ list: ["a", "b", "c"] })

  const newDoc = Automerge.change(
    doc,
    {
      patchCallback: (_, patchInfo) => {
        assert.deepEqual(
          patchInfo.before.list,
          ["a", "b", "c"],
          "before should be the original list"
        )
        assert.deepEqual(patchInfo.after.list, ["a", "c"])
      },
    },
    doc => {
      doc.list.deleteAt(1)
    }
  )
  assert.deepEqual(newDoc, { list: ["a", "c"] })
})
```

**Comment by orionz** [comment]
I tried your test on the `main` branch and tag `js/automerge-2.0.3` and in both cases the test passed.  What version of automerge are you seeing this behavior?
