### ISSUE TITLE
Proposal: Change the splice/marks path api

### ISSUE THREAD

**Issue by acurrieclark** [automerge/automerge#630]
When using, for example, `splice`, the function signature is:
```ts
function splice<T>(
  doc: Doc<T>,
  prop: stable.Prop,
  index: number,
  del: number,
  newText?: string
)
```
This obviously takes a doc (although I understand this could be any sub-section of a document tree too) and a path, which is a `Prop`. Essentially a string or a number.

If the property being edited is at the top level of your document, then this is straightforward. However, if it is nested:
```ts
type DocType = {
  file: {
    id: string;
    name: string;
    contents: string;
  }
}
```
then now the `path` needs to be `file/contents`, for example. The path needs to be separated by forward-slashes.

While this isn't unintuitive, I think there are 3 possible alternatives here.

1. Patches return a path in the form of `Prop[]`. Would it be sensible to pass a similar array here too?
2. Leave it as is
3. Move to "dot-path" style. This is commonly used outside of Automerge.

Whichever method we choose, there is the opportunity to add some type safety here too. `splice` and `mark` are both only valid within a `change` function callback, so (from the next release onwards) will be passed `<T>`, so we can infer from it without issue. For example:
```ts
function splice<T>(
  doc: T,
  prop: Path<T>,
  index: number,
  del: number,
  newText?: string
)
```
where `Path<T>` is a type checked value which is one of the above 3 options. I have types ready to go which would work for any of them, if required.

**Comment by alexjg** [comment]
I think using a `Prop[]` for the path instead of a string makes a lot of sense (and removes the need for fiddly logic around field names with `'\'` in them). What would `Path<T>` look like in that case?

**Comment by acurrieclark** [comment]
Something [like this](https://tsplay.dev/wg801N),

It's adapted from [this extraordinary typescript](https://github.com/g-makarov/dot-path-value/blob/main/src/index.ts) which is for dot paths

**Comment by alexjg** [comment]
I think what I'm more concerned about is that it seems likely we would need to use `splice` in scenarios where you don't know at compile time that the path is valid. In this case we would end up having to write an `as Path<T>` type cast right?

**Comment by acurrieclark** [comment]
True. For example taking a `Patch` path would just be a string array. Although that could be typed in the same way.

Exposing the `Path<T>` type would mean that consumers could use it to type their own function parameters, avoiding a large number of the issues.

I can see why you might hesitate to add the type checking. I think the pros would outweigh the cons for me though.

Should I put together a PR with the change to `Prop[]` first, then we can revisit the typing at a later date?

**Comment by alexjg** [comment]
I think including the `Path` type in the library so that users can use it is worth doing, we can include some documentation to the effect that you can use `Path` to ensure your paths are valid. I _don't_ think we should use it on `splice` or other functions that take a path because those functions should all also deal with dynamic paths. I don't want to add `Path<T>` to patches either as I am not _certain_ that would make sense.

Maybe it would make sense to expose slightly differently named versions of `splice` etc. which add this typesafe static path for people who want to use it? Maybe a module called `knownPath` or something so you can do `knownPath.splice`?

**Comment by acurrieclark** [comment]
Sounds like a good compromise to me. Will Get a PR together.
