### ISSUE TITLE
Type 'T[]' is not assignable to type 'List<T>' due to Extend<T> in js bindings

### ISSUE THREAD

**Issue by stephen** [automerge/automerge#633]
I was previously using `2.0.1-alpha.2` of `@automerge/automerge`. I have some code that looks like the equivalent of:
```ts
Automerge.change(Automerge.from({ list: [] }), (doc) => (doc.list = []));
```

I now get:
```
Type 'never[]' is not assignable to type 'List<never>'. ts(2322)
Type 'never[]' is missing the following properties from type 'List<never>': insertAt, deleteAt ts(2739)
```

(`never`s are unrelated - just because there's nothing in the array and ts can't infer the array type)

After the `Extend<T>` changes in https://github.com/automerge/automerge/commit/f428fe0169434782254b9f4320e9b4e7269c7bdb, it seems like resetting the array as above no longer works because normal arrays don't have `insertAt/deleteAt`.

these errors were generated in ts 4.9.4, but i briefly tested in the latest 5.1.3 and they still seem present.

**Comment by stephen** [comment]
relatedly, `Extend<T>` also causes this error for me:
```ts
const isDateEqual = (a: Date, b: Date) => {}; // ...
Automerge.change(Automerge.from({ d: new Date() }), (doc) => {
  isDateEqual(doc.d, new Date());
});
```

error output:
```
Argument of type '{ toString: {}; toDateString: {}; toTimeString: {}; toLocaleString: {}; toLocaleDateString: {}; toLocaleTimeString: {}; valueOf: {}; getTime: {}; getFullYear: {}; getUTCFullYear: {}; getMonth: {}; ... 32 more ...; [Symbol.toPrimitive]: {}; }' is not assignable to parameter of type 'Date'.
  Types of property 'toString' are incompatible.
    Type '{}' is not assignable to type '() => string'.
      Type '{}' provides no match for the signature '(): string'.ts(2345)
```
i have a hard time with conditional types, but perhaps it needs a branch case for function properties?

i feel like i must be doing something wrong because these both seem like common operations, but i couldn't find other issues talking about this..

**Comment by alexjg** [comment]
We just merged #622 which removes the `Extend` type because of exactly these problems. I'm working on pushing a release right now.

**Comment by stephen** [comment]
oof, thanks. i missed it while searching because i only looked in issues and not in pull requests 🙄

thank you!!

**Comment by alexjg** [comment]
Oh don't worry :slightly_smiling_face: . This is released at `2.1.0-alpha.4`, have a play and let us know if it doesn't solve your problem.

**Comment by stephen** [comment]
types look good, thanks! 

https://github.com/automerge/automerge/commit/b3a7ba0e9fba10e01d6b399a524a51039808a4b2 also seemed to fix an issue i had with the generics for `PatchInfo<T>`

**Comment by silasabbott** [comment]
I had the same issue in v2.0.3 with assigning arrays, and updating to v2.1.0-alpha.4 solved it too
