### ISSUE TITLE
Interaction between mark expand behavior and patches returned from change

### ISSUE THREAD

**Issue by jjallaire** [automerge/automerge#646]
Hi there, I'm working with the new marks API from `unstable` (so thrilled to see Peritext landing in Automerge!). I'm currently reproducing the basic logic of the Peritext bridge code (round-tripping Prosemirror transactions through Automerge before applying them, etc.)

One thing I noticed was that after round-tripping the `expand` property of marks isn't respected in the Prosemirror insertion. To investigate, I started by reproducing the "should handle expand marks" test (https://github.com/automerge/automerge/blob/main/rust/automerge-wasm/test/marks.ts#LL145C9-L145C35) and confirmed that the new API is working as expected in terms of what is returned from `Automerge.marks()`.

However, I also noted that the `Patch[]` returned from `Automerge.change()` does not include any "mark" patches (it just has a splice of the new text). You can see this illustrated in the code below (note the comments below calls to `console.log` is the output I observed):

```js
import { unstable as Automerge } from "@automerge/automerge";

import assert from "assert";

const TEXT_KEY = "text";

interface DocType {
  [TEXT_KEY]: string;
}

let doc = Automerge.init<DocType>();
doc = Automerge.change(doc, doc => {
  doc[TEXT_KEY] = "aaabbbccc";
  Automerge.mark(doc, TEXT_KEY, { start: 3, end: 6, expand: "both" }, "bold", true);
  const marks = Automerge.marks(doc, TEXT_KEY);
  assert.deepStrictEqual(marks, [{ name: 'bold', value: true, start: 3, end: 6 }]);
});

doc = Automerge.change(
  doc, 
  {
    patchCallback: (patches, info) => {
      console.log(patches);
      // 0 : {action: 'splice', path: Array(2), value: 'A'}
      // 1 : {action: 'splice', path: Array(2), value: 'A'}
    }
  },
  doc => {
    Automerge.splice(doc, TEXT_KEY, 6, 0, "A");
    Automerge.splice(doc, TEXT_KEY, 3, 0, "A");
    const marks = Automerge.marks(doc, TEXT_KEY);
    assert.deepStrictEqual(marks, [{ name: 'bold', value: true, start: 3, end: 8 }]);
  });

console.log(Automerge.marks(doc, TEXT_KEY));
// 0 :  {name: 'bold', value: true, start: 3, end: 8}
```

I could certainly imagine that these semantics are left to the caller -- i.e. the calling code ultimately knows which marks have `expand: 'after'` so could apply that logic when reconstructing Prosemirror marks from `Automerge.marks()`. However, I'm wondering if this is intentional or if it might be desirable for mark expansions implied by a splice to be included in the returned patches? I could certainly see it either way, just letting you know in case this is a defect or unexpected behavior.

Thanks again for your incredible work on both Automerge and Peritext!

**Comment by jjallaire** [comment]
A quick follow up: I've noted that it is possible to extract the mark context required to apply the right PM transaction using `Automerge.marks()` (i.e. the caller doesn't need to apply its special knowledge of mark behavior to get the right PM transaction). This may be the intended idiom (i.e. patches don't cover mark expansions since they can be reconstructed another way) in which case there is no issue here.

**Comment by alexjg** [comment]
In the latest automerge alpha (`2.1.0-alpha.5`) splice and insert patches _do_ include marks on them for precisely this reason :slightly_smiling_face: . You can see an example of using these in the (unfinished) work I am doing on a prosemirror integration here: https://github.com/alexjg/amg-prosemirror

Note that one of the things @orionz is working on is an extension to Peritext to express blocks in a way which will work nicely with prosemirror.

**Comment by jjallaire** [comment]
Wow, excellent! 

Tried it out and now see the `marks` field coming back in the splice. One thing I noticed is that `marks` are only coming back on splices at the beginning of the range (in spite of `expand: 'both'` being specified). Here's the modified test w/ the output of `console.log()` inline as comments:

```js
import { unstable as Automerge } from "@automerge/automerge";
import assert from "assert";

const TEXT_KEY = "text";
interface DocType {
  [TEXT_KEY]: string;
}

let doc = Automerge.init<DocType>();

doc = Automerge.change(doc, doc => {
  doc[TEXT_KEY] =  "aaabbbccc";
  Automerge.mark(doc, [TEXT_KEY], { start: 3, end: 6, expand: 'both' }, "bold", true);
  const marks = Automerge.marks(doc, TEXT_KEY);
  assert.deepStrictEqual(marks, [{ name: 'bold', value: true, start: 3, end: 6 }]);
});

doc = Automerge.change(
  doc, 
  {
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    patchCallback: (patches, _info) => {
      console.log(patches);
      // 0: {action: 'splice', path: ['text', 6], value: 'A'}
      // 1: {action: 'splice', path: ['text', 3], value: 'A', marks: {bold: true}}
    }
  },
  doc => {
    Automerge.splice(doc, [TEXT_KEY], 6, 0, "A");
    Automerge.splice(doc, [TEXT_KEY], 3, 0, "A");
    const marks = Automerge.marks(doc, TEXT_KEY);
    assert.deepStrictEqual(marks, [{ name: 'bold', value: true, start: 3, end: 8 }]);
  });

console.log(Automerge.marks(doc, TEXT_KEY));
// 0 :  {name: 'bold', value: true, start: 3, end: 8}
```

I would have expected:

```js
0: {action: 'splice', path: ['text', 6], value: 'A'}
```

To be:

```js
0: {action: 'splice', path: ['text', 6], value: 'A',  marks: {bold: true}}
```

Note that the full range is correctly reported by `Automerge.marks()` at the end.

Will take a closer look at https://github.com/alexjg/amg-prosemirror and follow up there as appropriate after comparing notes w/ my own explorations.

**Comment by mweidner037** [comment]
Insertions in the middle of an "after" span also get the right `SplicePatch.marks`, but not insertions at the end.

I've noticed this behavior for unmark spans too: insertions at the end are assigned `SplicePatch.marks` as if the unmark span wasn't there.

In `@automerge/automerge@2.1.0-alpha.12`:
```ts
(async function () {
  const { next: Automerge } = await import("@automerge/automerge");

  // Starting state: aBCCBa
  let doc = Automerge.from({ text: "abccba" });
  doc = Automerge.change(doc, (doc) =>
    Automerge.mark(
      doc,
      ["text"],
      { start: 1, end: 5, expand: "after" },
      "bold",
      true
    )
  );

  // Insert D in the middle of the bold span to get aBCDCBa:
  doc = Automerge.change(
    doc,
    { patchCallback: (patches) => console.log(patches) },
    (doc) => {
      Automerge.splice(doc, ["text"], 3, 0, "d");
    }
  );
  // Prints [{ action: 'splice', path: [ 'text', 3 ], value: 'd', marks: { bold: true } } ]
  // - okay.

  // Insert E at the end of the bold span to get aBCDCBEa:
  doc = Automerge.change(
    doc,
    { patchCallback: (patches) => console.log(patches) },
    (doc) => {
      Automerge.splice(doc, ["text"], 6, 0, "e");
    }
  );
  // Prints [ { action: 'splice', path: [ 'text', 6 ], value: 'e' } ]
  // - missing { bold: true } mark.

  console.log(Automerge.marks(doc, ["text"]));
  // Prints [ { name: 'bold', value: true, start: 1, end: 7 } ]
  // - the mark indeed applies to "e".
})();
```

**Comment by mweidner037** [comment]
@orionz The above code works in v2.1.6, but I still see missing marks in the patches when calling `applyChanges` on a *different* document.

Example:
```js
(async function () {
  const { next: Automerge } = await import("@automerge/automerge");

  // Starting state: A, bold, expand after.
  let doc1 = Automerge.from({ text: "A" });
  doc1 = Automerge.change(doc1, (doc) => {
    Automerge.mark(
      doc,
      ["text"],
      { start: 0, end: 1, expand: "after" },
      "bold",
      true
    );
    // Uncommment this op to see a different bug:
    // Automerge.mark(
    //   doc,
    //   ["text"],
    //   { start: 0, end: 1, expand: "after" },
    //   "italic",
    //   true
    // );
  });
  let doc2 = Automerge.load(Automerge.save(doc1));

  // Append char B.
  console.log("doc1 patches:");
  const oldDoc1 = doc1;
  doc1 = Automerge.change(
    doc1,
    {
      patchCallback: (patches) => console.log(patches),
    },
    (doc) => Automerge.splice(doc, ["text"], 1, 0, "B")
  );
  /* Prints:
        [
          {
            action: 'splice',
            path: [ 'text', 1 ],
            value: 'B',
            marks: { bold: true }
          }
        ]
    - okay.
  */

  // Deliver to doc2:
  const changes = Automerge.getChanges(oldDoc1, doc1);
  console.log("doc2 patches:");
  [doc2] = Automerge.applyChanges(doc2, changes, {
    patchCallback: (patches) => console.log(patches),
  });
  // Prints [ { action: 'splice', path: [ 'text', 1 ], value: 'B' } ]
  // - the marks are missing.

  console.log("doc2 marks:");
  console.log(Automerge.marks(doc2, ["text"]));
  // Prints [ { name: 'bold', value: true, start: 0, end: 2 } ]
  // - the mark indeed applies to "B".
})();
```

If you uncomment the second mark op (italic), then doc2 sees a "bold" mark in the patch but not an "italic" mark.

https://github.com/automerge/automerge/issues/716 was a similar (fixed) issue for `MarkPatch`s; this bug is for marks in `SplicePatch`s.
