### ISSUE TITLE
Automerge.Text chokes on emojis

### ISSUE THREAD

**Issue by stephen** [automerge/automerge#658]
repro:
```ts
import * as Automerge from "@automerge/automerge";
Automerge.from({ d: new Automerge.Text("👀👀") })
```

results in:
```
Uncaught 'index 1 is out of bounds'
```

I did some quick bisecting and it seems like the bug was introduced between `2.0.1-alpha.2` (working) and `2.0.1-alpha.3` (erroring).

**Comment by annabelle** [comment]
A workaround to this is to unpack the string before passing it to the constructor:

```js
import * as Automerge from "@automerge/automerge";
Automerge.from({ d: new Automerge.Text(..."👀👀") })
```
