### ISSUE TITLE
Automerge errors in js from automerge-wasm don't have stack traces

### ISSUE THREAD

**Issue by stephen** [automerge/automerge#659]
While investigating #658, I found it very tricky to pinpoint where this error was being thrown from because it seems like the errors are raw strings with no stacktraces attached:
```ts
import * as Automerge from "@automerge/automerge";
try {
  Automerge.from({ d: new Automerge.Text("👀👀") });
} catch (err) {
  console.log(typeof err);
  console.log(err);
}
```

outputs:
```
string
index 1 is out of bounds
```

It would be great if errors across the wasm boundary captured a stacktrace to make hunting down errors more possible. Without it, I ended up sticking `try {} catch {}` everywhere to pinpoint the problem.

**Comment by stephen** [comment]
I don't fully understand what's going on with errors on the js <> wasm boundary yet.. it seems like there might still be on-going work in wasm-bindgen (https://github.com/rustwasm/wasm-bindgen/issues/2389 and https://github.com/rustwasm/walrus/issues/67) for errors from wasm to work automatically.

In the meantime, wdyt about wrapping functions in the `@automerge/automerge` layer with a try/catch?

i.e. for proxies...
```ts
const ListHandler = {
  get(...) {
    try {
      // ...
    } catch (err) {
      // cause to preserve inner error: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/cause
      throw new Error(`failed to get element ${index} from list`, { cause: err })
    }
  }

  set(...) {
    try {
      // ...
    } catch (err) {
      throw new Error(`failed to set element ${index} on list`, { cause: err })
    }
  }
}
```

and maybe a few other functions like `change` and `from`

**Comment by alexjg** [comment]
Yeah the error handling across the JS/WASM boundary leaves a lot to be desired. The change you've suggested sounds extremely sensible though!

**Comment by stephen** [comment]
ok great! i will look into making a PR
