### ISSUE TITLE
Counter type inc/dec methods not available

### ISSUE THREAD

**Issue by acurrieclark** [automerge/automerge#662]
I was doing some benchmarking this morning, and went to use a `Counter` for the first time in a while.

In a simple document:

```ts
const docData = {
  counter: new Counter(0)
};

const doc = from(docData);

change(doc, (doc) => {
  doc.counter.increment(2);
})
```

use of the increment method causes a typescript error.

The class is defined here:
https://github.com/automerge/automerge/blob/89a0866272502f6360221d6585e93990f932de24/javascript/src/counter.ts#L8

and I can see that there is a separation, presumably with the aim of preventing changes outside of a `change` callback. The only way round this can see from a type perspective would be a return to the dark days of `Extend`.

Could we perhaps add methods with the same signature which throw an error? If `WritableCounter` is used inside the `change` callback, then its methods would be used when needed?

**Comment by acurrieclark** [comment]
Happy to PR for this if the above is considered a good idea

**Comment by alexjg** [comment]
Yeah methods which throw an error outside of the change callback seems like the least bad option to me.

**Comment by acurrieclark** [comment]
I love a least bad option. Will put together a PR

**Comment by acurrieclark** [comment]
Just one other thought. `Text` doesn't limit this at the moment, and provides the `insertAt` and `deleteAt` methods on the main class. We could just do that?
