### ISSUE TITLE
how to integrate automerge in webpack4. 

### ISSUE THREAD

**Issue by luoyiping250** [automerge/automerge#670]
hello,
as the title said: how to integrate automerge in webpack4 and how to do. the .wasm didnt work in webpack4.
thanks a lot.

**Comment by alexjg** [comment]
I'm not sure that webpack 4 ever managed to support WASM particularly well. There are some notes here: https://github.com/rustwasm/wasm-bindgen/issues/39. Are you able to update to webpack 5?

**Comment by luoyiping250** [comment]
i tried so many ways to solve it, but no work. i see, i have to update mywebpack.thank u all the same.
