### ISSUE TITLE
automerge-c: Enum type redefinition is incompatible with C++

### ISSUE THREAD

**Issue by jkankiewicz** [automerge/automerge#723]
The "automerge-c/automerge.h" header file generated by the `cbindgen` tool is incompatible with C++ because it converts a directive like `#[repr(u8)]` preceding a Rust declaration like `pub enum ExampleEnum {...` into a declaration like `typedef uint8_t ExampleEnum;` which follows the enum's corresponding declaration within the generated header file.
A C compiler tolerates the redefinition of the `ExampleEnum` type in this way but a C++ compiler doesn't so it precludes the automerge-c library from being used by a C++ application e.g.
```
error C2371: 'AMidxType': redefinition; different basic types
```

**Comment by alexjg** [comment]
Fixed by #724
