### ISSUE TITLE
Bundle wasm into JS source code

### ISSUE THREAD

**Issue by BlowaterNostr** [automerge/automerge#728]
The key of local first software is that the software continues to work when offline.

The WASM for JS binding is `fetch`ed, meaning it has to connect to the internet, making it not local-first at all.

**Comment by alexjg** [comment]
Could you describe a little what your build environment looks like? In most bundlers that I've encountered the WASM blob is part of the application bundle just like any other asset in the application and is consequently downloaded at the same time as the other assets, just like the JS source code. I'm wondering if you are building an application where the JS is bundled up and distributed in some manner but the bundling process doesn't know how to handle the WASM?

**Comment by BlowaterNostr** [comment]
@alexjg I am using Deno

**Comment by alexjg** [comment]
Ah I see. I think you might be running into #555 ?

**Comment by BlowaterNostr** [comment]
Yes, similar problem @alexjg
