### ISSUE TITLE
Unable to set object en masse to mutable doc within change callback

### ISSUE THREAD

**Issue by markmhx** [automerge/automerge#75]
I've found that the `doc` mutable object within a `Automerge.change` callback can't be set using another object directly, otherwise the changes are lost.

See the following case in which I try to set `doc` with an object's values directly during the "Initialize" change starting on line 5...

```
const Automerge = require('automerge');

let doc1 = Automerge.init();

doc1 = Automerge.change(doc1, 'Initialize', doc => {
  doc = {
    bar: 'zoop',
    foos: {
      doop: 1
    }
  };
});

console.log('doc1', doc1);

doc2 = Automerge.init();
doc2 = Automerge.merge(doc2, doc1);

doc1 = Automerge.change(doc1, 'Set foos doop to 5', doc => {
  doc.foos['doop'] = 5;
});

doc2 = Automerge.change(doc2, 'Set bar to zip', doc => {
  doc.bar = 'zip';
});

let finalDoc = Automerge.merge(doc1, doc2);

console.log(Automerge.getHistory(finalDoc).map(state => [state.change.message]));
console.log(finalDoc);
```

...which results in an empty `doc1` variable aside from its `_objectId` and the following error:

```
automerge-test $ node index.js 
doc1 { _objectId: '00000000-0000-0000-0000-000000000000' }
/private/var/www/automerge-test/index.js:20
  doc.foos['doop'] = 5;
                    ^

TypeError: Cannot set property 'doop' of undefined
    at Automerge.change.doc (/private/var/www/automerge-test/index.js:20:21)
    at Object.change (/private/var/www/automerge-test/node_modules/automerge/src/automerge.js:145:3)
    at Object.<anonymous> (/private/var/www/automerge-test/index.js:19:18)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
```

However, if I set the mutable `doc` object's properties individually...

```
const Automerge = require('automerge');

let doc1 = Automerge.init();

doc1 = Automerge.change(doc1, 'Initialize', doc => {
  doc.bar = 'zoop';
  doc.foos = {
    doop: 1
  };
});

console.log('doc1', doc1);

doc2 = Automerge.init();
doc2 = Automerge.merge(doc2, doc1);

doc1 = Automerge.change(doc1, 'Set foos doop to 5', doc => {
  doc.foos['doop'] = 5;
});

doc2 = Automerge.change(doc2, 'Set bar to zip', doc => {
  doc.bar = 'zip';
});

let finalDoc = Automerge.merge(doc1, doc2);

console.log(Automerge.getHistory(finalDoc).map(state => [state.change.message]));
console.log(finalDoc);
```

...then the changes are applied successfully:

```
automerge-test $ node index.js 
doc1 { _objectId: '00000000-0000-0000-0000-000000000000',
  bar: 'zoop',
  foos: { _objectId: '83c3523b-7c65-4a76-92e0-c476ccef33f0', doop: 1 } }
[ [ 'Initialize' ],
  [ 'Set foos doop to 5' ],
  [ 'Set bar to zip' ] ]
{ _objectId: '00000000-0000-0000-0000-000000000000',
  bar: 'zip',
  foos: { _objectId: '83c3523b-7c65-4a76-92e0-c476ccef33f0', doop: 5 } }
```

Perhaps this behavior is unintentional but I expected to be able to set the initial value of `doc1` with a multi-level object as such without problems so the behavior was unexpected.

**Comment by j-f1** [comment]
Does `Object.assign(doc, { ... })` in the function work?

**Comment by fueangfa** [comment]
I'm sory.

**Comment by markmhx** [comment]
@j-f1 Yep! That works

**Comment by ept** [comment]
Hi @markmhx, this is due to a fundamental limitation of the JavaScript language that we can't do anything about. When you assign to `doc` in your first change callback, you are simply overwriting the local variable `doc`; Automerge does not get informed about that variable assignment. Only when you assign to `doc.someProperty = value`, Automerge can pick up the fact that a property called `someProperty` was assigned `value` on the object `doc` (it uses [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) for this purpose).

Put another way, JavaScript does not allow us to override the `=` operator for assigning to variables; it only allows us to capture the `x.y = z` operator for assigning a property on an object.

**Comment by markmhx** [comment]
@ept Thanks for the explanation! Perhaps it's not worth the bother for just this use-case, but I wonder if generally it'd be cleaner to pass a plain object version of the doc to the change callback then convert it back into the immutable object via an inspection routine of sorts after the callback has finished. That's just a quick thought, though...no idea if it makes enough sense given the general system here.

Additionally, a sort of syntax that's more doc-based and avoids even the temptation to overwrite the doc object would feel more intuitive to me as well:

```
let doc1 = Automerge.init({
    bar: 'zoop',
    foos: {
      doop: 1
    }
});

let doc2 = Automerge.init(doc1);

doc1.set('foos.doop', 5, 'Set foos doop to 5');
doc2.set('bar', 'zip', 'Set bar to zip');

let finalDoc = Automerge.merge(doc1, doc2);

console.log(Automerge.getHistory(finalDoc).map(state => [state.change.message]));
console.log(finalDoc);
```

**Comment by ept** [comment]
The idea of passing an object to `Automerge.init()` is interesting; right now I don't think it's really necessary, but we might want to do something like that if we add support for schemas in the future.

Regarding the syntax `doc1.set('foos.doop', 5, 'Set foos doop to 5');` — that would imply that `doc1` is mutable, which we're deliberately avoiding. However, we have some work in progress for an [Immutable.js-compatible API](https://github.com/automerge/automerge/compare/immutable-write-interface), which will let you write `doc1 = doc1.setIn(['foos', 'doop'], 5)`, which is not too far from your suggestion.

**Comment by markmhx** [comment]
@ept Fantastic, thanks!

@mmcgrana Go go, gadget!
