### ISSUE TITLE
golang port

### ISSUE THREAD

**Issue by gedw99** [automerge/automerge#82]
Automerge looks highly useful in the non JS world too.

I would like to hear back from people about if they woudl be supportive of a port to golang.

You can compile golang to WASM and JS for use in browser and nodejs.
JavaScript:
https://github.com/gopherjs/gopherjs

Wasm:
https://go-review.googlesource.com/c/go/+/102835
Its offically supported and WASM is supported in all browsers now.

You can also use it for compiled GUI's. 
For example you can use it with Flutter.
https://github.com/flutter/flutter/issues/15925
You can compiel the golang code to AMD86 or ARMv8 (64bit) for use in emulators or real mobiles.

You can also use it on raspberry PI's etc etc or from cpp, c#, etc etc.

---

I like the fact that Automarge only does the logic and leaves it up to the developers how they want to integrate it with storage etc.
Also the same goes for how nodes communicate and what network transports they use.

I also think serverside there is huge potential for using Automerge / CRDT. There are a few high performance computing projects using CRDT to handle parrallel computing workloads for example.

I can imagine if a golang port occurs then wrapper for Protocol buffers and GRPC will happen.

---

I fully expect to be heavily criticised for discussing this as i can imagine if you are mostly programming in JavaScript you will view any port to golang as a negative thing. In some ways its true. But that is why i also highlighted that golang supports WASM now.

We could have 2 source versions of Automerge. But  the logic of how Automarge and CRDT works is rare and so its not that easy to maintain 2 source versions. But when looking at the code i can see its pretty clean code and not a huge amount of it.
Personally i would favour a single surce base in golang version and a compiled to WASM version.

---
Other ways to skin the same cat ?

There is one JS to golang compiler also, and maybe a few more.
https://github.com/jingweno/godzilla

There are 3 Javascript emulators written in golang also, but i dont think that route is optimal because they are slow.

Please be nice.. I expect many will not look at this issue favourable ..

**Comment by pvh** [comment]
A golang implementation sounds great. I'd be a little concerned about the difficulty of keeping various implementations in sync but automerge doesn't specify network protocols or storage so divergence is relatively benign.

I have heard talk from someone about a Rust Port as well, and I've given thought to a Dart port so that I could use automerge more easily from flutter.

I don't think shifting automerge to be a golang-first repository is a particularly productive conversation at this stage. If there were a fast implementation in another language with good bindings that worked in the browser then the conversation would be different, though still by no means settled.

**Comment by pvh** [comment]
Closing the issue since this isn't really an issue with the automerge repo but if there are specific documentation or technical questions please feel free to open issues for that or ask in the slack. 

Keep us abreast of your progress!

**Comment by gedw99** [comment]
@pvh 
Yeah i can really understand why you want to stick with the JS version.
So, i have gotten a JS to golang converter working. Not working yet, but the cleaness of the JS code makes it reasonably easy with a little fiddling.
I have to replace the immutable facebook js lib your using with a golang one though i think.

I am writing the conversion so that its indempotent and so i can take your JS and run it through the converter whenever you hit a release.

Happy to hear a Rust and Dart version are happening. 

Will let you know when i have something worth looking at.

**Comment by gedw99** [comment]
@pvh

I have finished the port and will publish it on GitHub.

Do you have a link to the person that is doing the Dart port. I can help with that too

**Comment by pvh** [comment]
That person is me and I haven't started but I'd love to see it!

**Comment by gedw99** [comment]
hehe :)

**Comment by wdullaer** [comment]
@gedw99 did you ever publish the code for this?
