### ISSUE TITLE
No docs for Map types?

### ISSUE THREAD

**Issue by callumlocke** [automerge/automerge#892]
I'm new to Automerge and reading through the docs. The [Document Data Model](https://automerge.org/docs/documents/) page mentions the three composite types (Map, List, and Text). List and Text have their own pages, but there doesn't seem to be any further documentation about the Map type?

**Comment by alexjg** [comment]
The map type is just a javascript object in the JS API. I.e. `Automerge.change(doc, d=> d.somemap = {})` creates a map in the `somemap` key of the root map in the document.

**Comment by callumlocke** [comment]
OK that makes sense. I'll close this but I'd suggest adding a page explaining it with examples similar to the List page
