### ISSUE TITLE
Error inflating document chunk ops: an operation referenced a missing actor id

### ISSUE THREAD

**Issue by wg** [automerge/automerge#897]
Hello!

I've run across an issue where automerge 0.5.9 generates invalid saves that give `error inflating document chunk ops: an operation referenced a missing actor id` when attempting to load them. I've managed to reproduce this in a minimized test case:

```rust
use anyhow::Result;
use automerge::{ActorId, AutoCommit, ReadDoc, ROOT};
use automerge::transaction::Transactable;

// error inflating document chunk ops: an operation referenced a missing actor id
fn main() -> Result<()> {
    let actor0 = ActorId::from(&[0]);
    let actor1 = ActorId::from(&[1]);
    let actor2 = ActorId::from(&[2]);

    let mut doc0 = AutoCommit::new().with_actor(actor0);
    doc0.put(ROOT, "a", 1)?;

    // swap these actors and no error occurs
    let mut doc1 = doc0.fork().with_actor(actor2);
    let mut doc2 = doc0.fork().with_actor(actor1);

    doc1.put(ROOT, "b", 2)?;
    doc2.merge(&mut doc1)?;
    doc2.delete(ROOT, "c")?;

    // error occurs here
    doc2.save_and_verify()?;

    println!("{:?}", doc2.get(ROOT, "a"));
    println!("{:?}", doc2.get(ROOT, "b"));
    println!("{:?}", doc2.get(ROOT, "c"));

    Ok(())
}
```

Interestingly it seems to depend on the ordering of ActorIDs as if you swap `actor1` and `actor2` the error doesn't occur. With random ActorIDs the problem is not 100% reproducible.

It also seems to be related to the `doc2.delete(ROOT, "c")` operation which has no effect since the key `"c"` isn't set in the document.

Anyhow, is this a bug or am I misusing the API somehow? The behavior doesn't seem to be present in 0.5.6. Thank you!

**Comment by issackelly** [comment]
We hit this bug fairly consistently today. I think we have the document in question, and it was a development document so no sensitive data is in it.

**Comment by alexjg** [comment]
I have a fix incoming
