### ISSUE TITLE
Error when performing Automerge.change() while Automerge.getMissingDeps() is non-empty

### ISSUE THREAD

**Issue by ept** [automerge/automerge#92]
@mmcgrana [reports](https://gist.github.com/mmcgrana/5f4d8391d959a14686ddda655e5c699e) the following issue:

```js
Automerge = require('automerge')

const docRoot = Automerge.init()

const doc1 = Automerge.change(docRoot, (doc) => {
  doc.foo = []
})
const change1 = Automerge.getChanges(docRoot, doc1)

const doc2 = Automerge.change(doc1, (doc) => {
  doc.foo.push('a')
})
const change2 = Automerge.getChanges(doc1, doc2)

console.log(change1, change1[0].ops)
console.log(change2, change2[0].ops)
console.log()

const docA = Automerge.applyChanges(docRoot, change2)
console.log(docA)
console.log(Automerge.getMissingDeps(docA))
// Line below throws e.g. `Modification of unknown object 860bacb9-eae2-4035-a257-4a2604c229f4`.
console.log(Automerge.change(docA, (doc) => { doc.biz = 'c' }))
console.log()

const docB = Automerge.applyChanges(docA, change1)
console.log(docB)
console.log(Automerge.getMissingDeps(docB))
console.log(Automerge.change(docB, (doc) => {doc.biz = 'd' }))

// Everything else above works as expected (if the offending line is commented out).

// The error only appears for certain types of blocks given to create doc1 and
// doc2. E.g. if doc1 is created with `(doc) => { doc.foo = 'bar' }` and doc2
// with `(doc) => {doc.foo = 'bat' }`, the error doesn't occur.
```

**Comment by ept** [comment]
The problem arises because all of the changes are being made on the same actor ID. Firstly, `change1` and `change2` are created as change number 1 and change number 2, respectively, of actor `docRoot._actorId`. Next, when you do `const docA = Automerge.applyChanges(docRoot, change2)`, it notices that change number 1 is missing, so change number 2 is not yet applied; thus, `docA` is still an empty document to which no changes have been applied.

Finally, when you do `Automerge.change(docA, (doc) => { ... })`, that causes a new **change number 1** for actor `docRoot._actorId` to be created. Now that change number 1 is filled in, Automerge thinks it should be able to apply the `change2` from earlier. Unfortunately, `change2` depended on a different `change1` than the change number 1 we have just applied, and thus Automerge's internal data structure is left in an inconsistent state.

How best to fix this? The most obvious step would be to ensure that `Automerge.change(docA, (doc) => { ... })` produces a change number 3, not change number 1. That is, it should take note of the queued change number 2 when assigning change numbers.

However, I fear there might be a deeper problem here. For example, the following code would still break, even if we fix the change number assignment:

```js
const doc0 = Automerge.init()
const doc1 = Automerge.change(doc0, doc => { doc.foo = [] })
const doc2 = Automerge.change(doc1, doc => { doc.foo.push('a') })
const change1 = Automerge.getChanges(doc0, doc1)
const change2 = Automerge.getChanges(doc1, doc2)
const doc1a = Automerge.applyChanges(doc0, change1)
const doc2a = Automerge.change(doc1a, doc => { doc.biz = 'c' })
Automerge.applyChanges(doc2a, change2)
// Throws: Inconsistent reuse of sequence number 2 by a9e29347-63ac-42de-b2f8-a99d0bac54e8
```

In both your example and my example above, the fundamental problem is that we are accidentally creating two different changes that have the same actor and the same sequence number. This happens because, in both examples, the change `doc.biz = 'c'` is being made to a document that originates from the same `Automerge.init()`, but that document does not have all the preceding changes made by that actor ID.

I think the "correct" fix would be to ensure that any `Automerge.change` calls are made on an actor ID that is always moving forwards. Perhaps this could be enforced by making `Automerge.applyChanges` refuse to apply any changes that originated on the same actor ID, which would allow this problematic pattern to be detected earlier. What do you think?

**Comment by mmcgrana** [comment]
Thanks for taking a look @ept!

It does seem reasonable to me that `Automerge.change` calls are made on an actor ID that's always moving forwards.

I think `Automerge.applyChanges` refusing any changes originating on the same `actorID` may be problematic if you're applying changes that you're loading from storage for yourself, where you're maintaining your `actorID` across sessions. This happens in Hypermerge, where the `actorId` is consistent across time for a given {Hypermerge doc, user device}. (Happy to elaborate on this if helpful). Note that Hypermerge does prevent the user from initiating `Hypermerge.change` calls while their own actor's changes are being loaded from disk and applied, so I think it avoids at least the obvious way to violate the invariant of always moving forward for a given `actorId`. We could say that a persistent `actorId` like this is bad and you just shouldn't do it - would you say that? Adapting to that would require changes in Hypermerge that I haven't designed but it seems tractable.

In this reproduction I only used one `actorId`, but in the original bug in our app there's an actor per user, so now I'm wondering if this reproduction actually captures the issue we saw in the app. I'm not sure where we could be `Automerge.change` calls on an actor ID that isn't moving forwards. I'll think about that some more, and can also see if a similar reproduction works with multiple actors.

**Comment by ept** [comment]
> We could say that a persistent `actorId` like this is bad and you just shouldn't do it - would you say that?

I wouldn't say that — in fact, Hypermerge's use of a persistent actor ID seems reasonable and logical to me. But we do need to ensure that `Automerge.change` can only be called on a document to which **all** prior changes from the same `actorID` (and any changes they depend on) have been applied. That would satisfy the "moving only forwards through time" principle.

**Comment by mmcgrana** [comment]
@ept OK gotcha.

> But we do need to ensure that Automerge.change can only be called on a document to which all prior changes from the same actorID (and any changes they depend on) have been applied

I do think we're enforcing this so am not sure where the error might be coming from. I'll keep looking into it and see if I can get more helpful tracing info.

For the record I did try the repro code with multiple actors and it worked without errors as expected: https://gist.github.com/mmcgrana/d33d8c6e7e93d42f82b93336bf63b5e4.

**Comment by ept** [comment]
I'm going to close this issue because there is no clear need to change anything in Automerge right now. Ensuring that we don't reuse sequence numbers is something that has to be done at the Hypermerge level. Generally there may be some API ergonomics improvements that we could make to reduce the risk of using Automerge wrongly, but it's not clear to me at the moment what they would look like.
