### ISSUE TITLE
generatySyncMessage --> no changes tracked, automerge 2.2.4

### ISSUE THREAD

**Issue by mcchran** [automerge/automerge#945]
Hello team!

First things first, kudos for the project!

I am using automerge v2.2.4 to sync docs across multiple clients. I am not using the automerge-repo FYI. So I came across the following problem while generating a SyncMessage to share over the network:

In the example bellow `dummyChanges` is a list of all changes perform to the document.
However these changes are not included in the `msg` generated by the `automerge.generateSyncMessage` function. `msg` is not nil it just does not include any changes.

```
        const dummyDoc = automerge.change(automerge.from(
            {content: ""}), doc => { doc.content = "dummy" })
        console.log("document to be sent is: ", dummyDoc)
        const dummyChanges = automerge.getAllChanges(dummyDoc)
        console.log(dummyChanges)
        let dummyState = automerge.initSyncState()
        let msg: Uint8Array | null = null;
        [dummyState, msg] = automerge.generateSyncMessage(dummyDoc, dummyState)

        if (msg) {
            console.log("the decoded message is: ")
            console.log(automerge.decodeSyncMessage(msg))
        }
```

Any idea ? 

I am not sure if I miss anything here, there is plenty of documentation out there (some of it outdated) so I am little bit confused regarding  iff this is an issue ... 

Cheer,
C.

**Comment by alexjg** [comment]
The first message that automerge sends doesn't contain changes, it just contains a summary of the changes the sender has. The receiver will then send back a summary of the changes they have, along with some changes they think the sender needs. This process repeats.

**Comment by mcchran** [comment]
In that case once the reciveSyncMessage is invokes (by PeerB) it should generate a message to send back to peerA. That is not happening though. The message generated by reciveSyncMessage is null which suggests that there are no changes between the two docs. ... which does not apply to my case.

**Comment by nasser** [comment]
I can confirm and reproduce on 2.2.8

```js
import { next as automerge } from "@automerge/automerge"

const a = {
    doc: automerge.init(),
    sync: automerge.initSyncState()
}

const b = {
    doc: automerge.init(),
    sync: automerge.initSyncState()
}

a.doc = automerge.change(a.doc, doc => doc.changes = true)

const [sync1, message1] = automerge.generateSyncMessage(a.doc, a.sync)
a.sync = sync1

if (!message1) throw 'no message1'

const [newDoc1, sync2, message2] = automerge.receiveSyncMessage(b.doc, b.sync, message1)
b.doc = newDoc1
b.sync = sync2

console.log(a.doc, b.doc, message2)
// { changes: true } {} null
```

**Comment by alexjg** [comment]
Ah, I see the problem. The issue is that the documentation for `receiveSyncMessage` is wrong. It states that `receiveSyncMessage` returns a new sync message to send, but this is not true, it's left over from a previous API. You always have to call `generateSyncMessage` to see if there's another message to send. This snippet does what I think You expect:

```
import { next as automerge } from "@automerge/automerge"

const a = {
    doc: automerge.init(),
    sync: automerge.initSyncState()
}

const b = {
    doc: automerge.init(),
    sync: automerge.initSyncState()
}

a.doc = automerge.change(a.doc, doc => doc.changes = true)

const [sync1, message1] = automerge.generateSyncMessage(a.doc, a.sync)
a.sync = sync1

if (!message1) throw 'no message1'

let [newDoc1, sync2] = automerge.receiveSyncMessage(b.doc, b.sync, message1)
b.doc = newDoc1
b.sync = sync2

let message2
[sync2, message2] = automerge.generateSyncMessage(b.doc, b.sync)
b.sync = sync2

console.log(a.sync)
console.log(b.sync)
console.log(a.doc, b.doc, message2)
```

I'll fix that documentation immediately, it's very confusing.

**Comment by nasser** [comment]
confirmed working -- thank you!

```js
import * as automerge from "@automerge/automerge"

function send(client) {
    const [sync, message] = automerge.generateSyncMessage(client.doc, client.sync)
    client.sync = sync
    return message
}

function receive(client, message) {
    const [doc, sync] = automerge.receiveSyncMessage(client.doc, client.sync, message)
    client.doc = doc
    client.sync = sync

    const [syncResponse, messageResponse] = automerge.generateSyncMessage(client.doc, client.sync)
    if (messageResponse) {
        client.sync = syncResponse
        return messageResponse
    } else {
        return null
    }
}

const a = {
    doc: automerge.init(),
    sync: automerge.initSyncState()
}

const b = {
    doc: automerge.init(),
    sync: automerge.initSyncState()
}

a.doc = automerge.change(a.doc, doc => doc.changes = true)

const m1 = send(a)
const m2 = receive(b, m1)
const m3 = receive(a, m2)
const m4 = receive(b, m3)
const m5 = receive(a, m4)

if(m5 !== null) throw 'unexpected'

console.log(a.doc, b.doc)
// { changes: true } { changes: true }
```

**Comment by alexjg** [comment]
I've updated the docs in #967. I'm leaving the type signature as is for now though because it would be a breaking change to fix it. We'll update the type signature in the next major release.

**Comment by nasser** [comment]
amazing -- thanks for turning this around so quickly!
