### ISSUE TITLE
Communicating changes over the network

### ISSUE THREAD

**Issue by nomve** [automerge/automerge#96]
Hi,

first of all, thanks for the really cool work! I have a question about how the changes are supposed to be sent over the network and then merged. I hope the question is not too long, but I will mostly copy your code examples. In the docs you have this:

```
let doc1 = Automerge.init()
// apply changes to doc1

// Now let's simulate another device, whose application state is doc2. We
// initialise it separately, and merge doc1 into it. After merging, doc2 has
// a copy of all the cards in doc1.

let doc2 = Automerge.init()
doc2 = Automerge.merge(doc2, doc1)
```
This works, but we basically have the doc1 instance already. In a real life example, we would need to do something like this, correct?
```
serialized = Automerge.save(doc1) // send it over the network
doc2 = Automerge.merge(Automerge.init(), Automerge.load(serialized))
```
This also works, but what I have found is that basically passing back `doc2` to `doc1` only really works as long as I have the same instance of `doc1`. If I reinit `doc1` and apply some previously known state (e.g. a simple object), then merging is most of the time unsuccessful. If I can reinit `doc1` with `Automerge.load` then it still works. So using `Automerge.load` is essential if for instance one of the clients e.g. shuts down or in any way loses the instance of the doc. Is this correct?

**Comment by ept** [comment]
Hi @nomve, there are a [few different ways](https://github.com/automerge/automerge#sending-and-receiving-changes) of doing the network communication. You can use [Hypermerge](https://github.com/automerge/hypermerge) or [MPL](https://github.com/automerge/mpl), which run Automerge over peer-to-peer network protocols (Dat and WebRTC respectively), you can use [Automerge.Connection](https://github.com/automerge/automerge/blob/master/src/connection.js) over a one-to-one connection between peers (e.g. a direct TCP connection), or you can build a protocol yourself using [`getChanges()` and `applyChanges()`](https://github.com/automerge/automerge#sending-and-receiving-changes).

`Automerge.load()` and `Automerge.save()` are intended for saving your state to local disk; you wouldn't normally send that state over the network.

What do you mean with merging being unsuccessful? Can you give me a code sample that throws an exception or produces an unexpected result?

**Comment by nomve** [comment]
Hi @ept,

I've tried `getChanges`/`applyChanges`, but I don't get how to pass the current state of one client to the other, so the other can do its changes and send the changes back. From the docs:

```
// On one node
newDoc = Automerge.change(currentDoc, doc => {
  // make arbitrary change to the document
})
let changes = Automerge.getChanges(currentDoc, newDoc)
network.broadcast(JSON.stringify(changes))

// On another node
let changes = JSON.parse(network.receive())
newDoc = Automerge.applyChanges(currentDoc, changes)
```
on both nodes we have `currentDoc`, how do we get the same initial state on both nodes? Or the state of one node to the other. This doesn't work:

```
const initialState = {a: 1};

const node1 = Automerge.change(Automerge.init(), function (doc) {
    doc.state = initialState;
});

const node2 = Automerge.change(Automerge.init(), function (doc) {
    doc.state = initialState;
});

const node2update = Automerge.change(node1, function (doc) {
    doc.state.b = 2;
})

const final = Automerge.applyChanges(node1, JSON.parse(JSON.stringify(Automerge.getChanges(node2, node2update))))

console.log(JSON.stringify(final))
```

throws `RangeError: Cannot diff two states that have diverged`. Changing `node2` to this fixes the issue:
```
const node2 = Automerge.load(Automerge.save(node1));
```

But since you say `Automerge.save` should not be used for sending data over the network, I guess I'm misunderstanding something here :).

The issue is similar with `Automerge.merge`. 
```
// Now let's simulate another device, whose application state is doc2. We
// initialise it separately, and merge doc1 into it. After merging, doc2 has
// a copy of all the cards in doc1.

let doc2 = Automerge.init()
doc2 = Automerge.merge(doc2, doc1)
```

If they were really two devices, how would we get `doc1` on the other device?

**Comment by ept** [comment]
Hi @nomve, try this:

```js
const node1 = Automerge.change(Automerge.init(), function (doc) {
    doc.state = initialState;
});

// This change sets the initial state. Send it via the network
const data1 = JSON.stringify(Automerge.getChanges(Automerge.init(), node1));

// Initialize node2 by making a new Automerge doc and applying data1 to it
const node2 = Automerge.applyChanges(Automerge.init(), JSON.parse(data1));

const node2update = Automerge.change(node2, function (doc) {
    doc.state.b = 2;
})

// Encode the change from node2 to node2update (i.e. setting doc.state.b)
const data2 = JSON.stringify(Automerge.getChanges(node2, node2update))

// Apply that change on node1
const node1update = Automerge.applyChanges(node1, JSON.parse(data2));
```

Does that make sense? Perhaps we need to improve the documentation to make this clearer.

**Comment by nomve** [comment]
I'm pretty sure it will work. The part of `Automerge.getChanges(Automerge.init(), node1)` is something I didn't figure out. Thank you very much :)

**Comment by ept** [comment]
Yes, that's not totally obvious. `Automerge.getChanges(Automerge.init(), node1)` will give you all the changes that happened since the creation of `node1`, and you can use them to initialise another node. Thereafter you would incrementally fetch just the changes that you haven't sent yet (as it would be inefficient to send the full list of changes repeatedly).

**Comment by ept** [comment]
An update for anyone looking at this old issue: there is now a new API. Instead of `Automerge.getChanges(Automerge.init(), node1)` you can just say `Automerge.getAllChanges(node1)`.
