### ISSUE TITLE
Is this expected behavior?

### ISSUE THREAD

**Issue by coodoo** [automerge/automerge#98]
In short, I created two docs namely `doc1` and `doc2`, then `doc2` deleted the first item in the list, while `doc1` changed the value of the first item, I was expecting the final list should be empty but instead got one item of value 'dd' inside, wondering is this expected result of the merge algorithm?

```js
console.clear()
const A = require('automerge')

let doc1 = A.init('DOC_1')

doc1 = A.change( doc1, '', doc => {
	doc.foo = ['a']
})

let doc2 = A.init('DOC_2')
doc2 = A.merge(doc2, doc1)

doc2 = A.change( doc2, '', doc => {
	doc.foo[0] = 'dd'
})

doc1 = A.change( doc1, '', doc => {
	delete doc.foo[0]
})

// Expect an empty array, but got ['dd']
let truthA = A.merge( doc1, doc2 )
// let truthB = A.merge( doc2, doc1 )

A.getHistory(doc2).map( s => console.log(s.change))
// console.log( '\n' )
A.getHistory(truthA).map( s => console.log(s.change))
```

**Comment by ept** [comment]
Hi @coodoo, that behaviour is intended. However, if it doesn't match your expectation or the needs of your application, I'd love to hear more about the situation in which you want the behaviour to be different.

My justification for the behaviour is as follows: `doc.foo[0] = 'dd'` has the effect of removing the value `'a'` from `doc.foo[0]`, and setting the value `'dd'` on `doc.foo[0]`. Concurrently, `delete doc.foo[0]` has the effect of removing the value `'a'` from `doc.foo[0]`. Thus, on both sides we remove `'a'`. On the doc2 side we additionally set `'dd'`. Combining both removals of `'a'` and the addition of `'dd'` leaves us in the final state `'dd'`.

**Comment by coodoo** [comment]
Interesting, I thought the order of execution from both docs will be considered when materializing the final view, in this case since doc1 deleted foo[0] at the last step, I would expect the final merged result is an empty array?

Or asked in another way, what operation and when will cause foo[0] be deleted?

**Comment by ept** [comment]
In your example, the relative order of `doc.foo[0] = 'dd'` and `delete doc.foo[0]` is not defined: the two changes happen without knowledge of each other, so we call them _concurrent_. Thus, no matter in which order those two changes get applied, the outcome must be the same (that is what Automerge guarantees).

To help understand what's going on, consider a different example: say you have `doc.foo[0] = 'dd'` on one document, and concurrently `doc.foo[0] = 'ee'` on the other document. When merged together, there are two different values (dd and ee) attached to the same list element `doc.foo[0]`. Automerge handles this by picking one of the two as the default, and keeping the other one in `doc.foo._conflicts`.

As you can see from that example, in general, there can be several values attached to a single list element. What `delete doc.foo[0]` does is to remove all current values from the list element — that is, it removes all values that were there at the time when the command `delete doc.foo[0]` was run. However, in your example, the value `'dd'` was not yet attached to `doc.foo[0]` at the time when `delete doc.foo[0]` was run. Therefore, the value `'dd'` is not deleted, and so it remains attached to `doc.foo[0]` when the changes are merged.

**Comment by coodoo** [comment]
> However, in your example, the value 'dd' was not yet attached to doc.foo[0] at the time when delete doc.foo[0] was run. Therefore, the value 'dd' is not deleted, and so it remains attached to doc.foo[0] when the changes are merged.

While trying to wrap my head around this comment I tried following instead:

```js
const m1 = A.merge(doc2, doc1)
A.getHistory(m1).map(h => console.log(h.change))
```

and here's the history replay result, see those marked in red boxes, seems to me `dd` was added first then later the `delete` was run, and yet `dd` remained in the list? or the history doesn't imply the order of application for each `OpSet`?

<img width="855" alt="screen shot 2018-06-18 at 6 10 57 pm" src="https://user-images.githubusercontent.com/325936/41548489-7506ee88-7323-11e8-915f-e05ebccf1aae.png">

**Comment by ept** [comment]
`getHistory()` shows the changes in the order they were applied to each document. If you do the merge the other way round…

```js
const m2 = A.merge(doc1, doc2)
A.getHistory(m2)
```

…you'll see that in `m1` the assignment of `dd` was applied first, and the deletion happened second; while on `m2` the deletion happened first, and the assignment of `dd` happened second.

That is the fundamental problem that Automerge needs to solve: changes arrive in a different order on different devices, and still, the final merged result has got to be the same. In this example, if you look at the order of operations on `m2`, the final result makes intuitive sense (assigning 'dd' happened second, so that's the final state).

Imagine we were to change the behaviour of Automerge so that in your example, the deletion takes precedence. Then the history of `m1` would be intuitive, but instead the history of `m2` would be surprising. Whichever way you turn it, it will look weird sometimes!

Hope that makes some sense. I don't know how to explain it any better.

**Comment by coodoo** [comment]
Thanks @ept for your patience and detailed explanations, those all made perfect sense.

After a couple more experimentations I found that the rule for merging is: when operating on the same spot (in this case `doc.foo`), `del` has higher priority over `set`, which mean deletion will run before insertion, hence the final result is `dd`

Also if there are two `set` on the same spot, it means there's a conflict, under this situation the one with higher actor id (vector clock) will win out, in this case `DOC_2` wins over `DOC_1` and `DOC_1`'s version will be stored in the `conflicts` set.

As long as these set of merging rules are applied across all actors, the final data is guaranteed to be the same, which is exactly what automerge is doing here, all's good now, great job btw :)
